In [506]:
# starting with content based filtering

In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [508]:
# loading the data from a CSV file to pandas data
df1 = pd.read_csv("../dataset/tmdb_5000_credits.csv")
df1.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [509]:
# loading the data from a CSV file to pandas data
df2 = pd.read_csv("../dataset/tmdb_5000_movies.csv")
df2.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [510]:
df = df1.merge(df2 , on="title" , how='inner')
df.head(2)

,movie_id,title,cast,crew,budget,genres,homepage,id,keywords,original_language,...,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,vote_average,vote_count
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,...,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,7.2,11800
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,...,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",6.9,4500

In [511]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   movie_id              4809 non-null   int64
 1   title                 4809 non-null   object
 2   cast                  4809 non-null   object
 3   crew                  4809 non-null   object
 4   budget                4809 non-null   int64
 5   genres                4809 non-null   object
 6   homepage              1713 non-null   object
 7   id                    4809 non-null   int64
 8   keywords              4809 non-null   object
 9   original_language     4809 non-null   object
 10  original_title        4809 non-null   object
 11  overview              4806 non-null   object
 12  popularity            4809 non-null   float64
 13  production_companies  4809 non-null   object
 14  production_countries  4809 non-null   object
 15  release_date          4808 non-null   object
 16  revenue               4809 non-null   int64
 17  runtime               4807 non-null   float64
 18  spoken_languages      4809 non-null   object
 19  status                4809 non-null   object
 20  tagline               3965 non-null   object
 21  vote_average          4809 non-null   float64
 22  vote_count            4809 non-null   int64
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [512]:
selected_features = ['movie_id' , 'title','overview' , 'genres','keywords','cast','crew']
print(selected_features)
df[selected_features].isnull().sum()

['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [513]:
# Checking for Null values and filling it with empty string.
# for feature in selected_features:
#     df[feature] = df[feature].fillna('')
df.dropna(inplace=True)
df[selected_features].isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [514]:
df.iloc[0][selected_features]

movie_id                                                19995
title                                                  Avatar
overview    In the 22nd century, a paraplegic Marine is di...
genres      [{"id": 28, "name": "Action"}, {"id": 12, "nam...
keywords    [{"id": 1463, "name": "culture clash"}, {"id":...
cast        [{"cast_id": 242, "character": "Jake Sully", "...
crew        [{"credit_id": "52fe48009251416c750aca23", "de...
Name: 0, dtype: object

In [515]:
import json
def preprocess(x):
    L = []
    for i in x:
        L.append(i["name"])
    return L

def preprocess_cast(x):
    L = []
    for i in x[:3]:
        L.append(i["name"])
    return L
# preprocess(json.loads(df.iloc[0]['genres']))
df['genres'] = df['genres'].apply(json.loads).apply(preprocess)
df['keywords'] = df['keywords'].apply(json.loads).apply(preprocess)
df['cast'] = df['cast'].apply(json.loads).apply(preprocess_cast)
df['crew'] = df['crew'].apply(json.loads).apply(lambda x: [i['name'] for i in x if i['job'] == 'Director'])

In [516]:
df[selected_features].iloc[0]

movie_id                                                19995
title                                                  Avatar
overview    In the 22nd century, a paraplegic Marine is di...
genres          [Action, Adventure, Fantasy, Science Fiction]
keywords    [culture clash, future, space war, space colon...
cast         [Sam Worthington, Zoe Saldana, Sigourney Weaver]
crew                                          [James Cameron]
Name: 0, dtype: object

In [517]:
df['genres'] = df['genres'].apply(lambda x: [i.replace(" ","") for i in x])
df['keywords'] = df['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
df['cast'] = df['cast'].apply(lambda x: [i.replace(" ","") for i in x])
df['crew'] = df['crew'].apply(lambda x: [i.replace(" ","")  for i in x])

In [518]:
df[selected_features].iloc[0]

movie_id                                                19995
title                                                  Avatar
overview    In the 22nd century, a paraplegic Marine is di...
genres           [Action, Adventure, Fantasy, ScienceFiction]
keywords    [cultureclash, future, spacewar, spacecolony, ...
cast            [SamWorthington, ZoeSaldana, SigourneyWeaver]
crew                                           [JamesCameron]
Name: 0, dtype: object

In [519]:
# Combining all the 5 selected features
combined_string = (
    df['overview'] * 1 + " " +
    df['genres'].apply(lambda x: " ".join(x)) * 3 + " " +
    df['keywords'].apply(lambda x: " ".join(x)) * 2 + " " +
    df['cast'].apply(lambda x: " ".join(x)) * 2 + " " +
    df['crew'].apply(lambda x: " ".join(x)) * 2
)
df['tags'] = combined_string.apply(lambda x: x.lower())

In [520]:
df_new = df[['movie_id','title','tags']]
df_new.head(1)

   movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a paraplegic marine is di...

In [535]:
df_new.to_csv("../dataset_cleaned/output.csv", index=False)

In [521]:
df_new['clean_title'] = (
    df_new['title']
    .astype(str)
    .str.lower()
    .str.replace(r'[^a-z0-9]', '', regex=True)
)

C:\Users\kousi\AppData\Local\Temp\ipykernel_65688\3832098366.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['clean_title'] = (

In [522]:
# # Converting all the Text Data to Numbering vectors
# vectorizer = TfidfVectorizer()
# feature_vectors = vectorizer.fit_transform(df_new['clean_title'] + ' ' + df_new['tags'])

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000 , stop_words='english')
feature_vectors = cv.fit_transform(df_new['tags'])
feature_vectors.shape

(1494, 5000)

In [523]:
# Cosine similarity of all the feature vectors
# The Thing it does is that bruteforce From Row1 to all the Rows in the DataFrame.
similarity = cosine_similarity(feature_vectors)
similarity.shape

(1494, 1494)

In [524]:
len(similarity[0])

1494

In [525]:
df_new["clean_title"].iloc[1]

'piratesofthecaribbeanatworldsend'

In [526]:
movie_names = df_new['clean_title'].tolist()
movie_names[:10]

['avatar',
 'piratesofthecaribbeanatworldsend',
 'spectre',
 'thedarkknightrises',
 'johncarter',
 'spiderman3',
 'tangled',
 'avengersageofultron',
 'harrypotterandthehalfbloodprince',
 'batmanvsupermandawnofjustice']

In [527]:
df_new.head(2)

,movie_id,title,tags,clean_title
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di...",avatar
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha...",piratesofthecaribbeanatworldsend

In [528]:
# rapidfuzz we are using to find the closest Match.
# Let us say if there are any spelling mistakes in the input array
# we need the correct spelling to find the index and check the cosine similarity
from rapidfuzz import process

movies = df_new['clean_title'].tolist()

user_input = "ironman"

find_close_match = process.extract(user_input, movies , limit=5)

print(find_close_match)

[('ironman', 100.0, 56), ('ironman3', 93.33333333333333, 27), ('ironman2', 93.33333333333333, 64), ('harleydavidsonandthemarlboroman', 75.00000000000001, 825), ('room', 67.5, 1043)]

In [529]:
df_new['clean_title'].tolist()

['avatar',
 'piratesofthecaribbeanatworldsend',
 'spectre',
 'thedarkknightrises',
 'johncarter',
 'spiderman3',
 'tangled',
 'avengersageofultron',
 'harrypotterandthehalfbloodprince',
 'batmanvsupermandawnofjustice',
 'quantumofsolace',
 'piratesofthecaribbeandeadmanschest',
 'theloneranger',
 'manofsteel',
 'theavengers',
 'piratesofthecaribbeanonstrangertides',
 'meninblack3',
 'thehobbitthebattleofthefivearmies',
 'theamazingspiderman',
 'robinhood',
 'thehobbitthedesolationofsmaug',
 'thegoldencompass',
 'titanic',
 'captainamericacivilwar',
 'jurassicworld',
 'skyfall',
 'spiderman2',
 'ironman3',
 'aliceinwonderland',
 'transformersrevengeofthefallen',
 'transformersageofextinction',
 'ozthegreatandpowerful',
 'theamazingspiderman2',
 'tronlegacy',
 'cars2',
 'greenlantern',
 'toystory3',
 'terminatorsalvation',
 'furious7',
 'worldwarz',
 'xmendaysoffuturepast',
 'jackthegiantslayer',
 'princeofpersiathesandsoftime',
 'pacificrim',
 'transformersdarkofthemoon',
 'indianajonesandthekingdomofthecrystalskull',
 'thegooddinosaur',
 'brave',
 'walle',
 '2012',
 'achristmascarol',
 'jupiterascending',
 'thelegendoftarzan',
 'xmenapocalypse',
 'thedarkknight',
 'monstersvsaliens',
 'ironman',
 'hugo',
 'themummytombofthedragonemperor',
 'suicidesquad',
 'evanalmighty',
 'edgeoftomorrow',
 'gijoetheriseofcobra',
 'insideout',
 'ironman2',
 'snowwhiteandthehuntsman',
 'maleficent',
 'dawnoftheplanetoftheapes',
 'captainamericathewintersoldier',
 'shrekforeverafter',
 'tomorrowland',
 'bighero6',
 'wreckitralph',
 'independencedayresurgence',
 'howtotrainyourdragon',
 'guardiansofthegalaxy',
 'interstellar',
 'inception',
 'thehobbitanunexpectedjourney',
 'thecuriouscaseofbenjaminbutton',
 'xmenfirstclass',
 'thehungergamesmockingjaypart2',
 'thesorcerersapprentice',
 'poseidon',
 'alicethroughthelookingglass',
 'shrekthethird',
 'warcraft',
 'terminatorgenisys',
 'transformers',
 'harrypotterandtheorderofthephoenix',
 'harrypotterandthegobletoffire',
 'hancock',
 'iamlegend',
 'charlieandthechocolatefactory',
 'ratatouille',
 'batmanbegins',
 'madagascarescape2africa',
 'nightatthemuseumbattleofthesmithsonian',
 'xmenoriginswolverine',
 'frozen',
 'thorthedarkworld',
 'madmaxfuryroad',
 'thor',
 'bolt',
 'gforce',
 'wrathofthetitans',
 'darkshadows',
 'missionimpossibleroguenation',
 'thewolfman',
 'beemovie',
 'kungfupanda2',
 'thelastairbender',
 'missionimpossibleiii',
 'marsneedsmoms',
 'flushedaway',
 'dieanotherday',
 'ghostbusters',
 'meninblackii',
 'beowulf',
 'kungfupanda3',
 'missionimpossibleghostprotocol',
 'riseoftheguardians',
 'funwithdickandjane',
 'exodusgodsandkings',
 'spiderman',
 'howtotrainyourdragon2',
 'watchmen',
 'captainamericathefirstavenger',
 'theworldisnotenough',
 'masterandcommanderthefarsideoftheworld',
 'happyfeettwo',
 'thebfg',
 'therevenant',
 'turbo',
 'rango',
 'thebourneultimatum',
 'kungfupanda',
 'antman',
 'thehungergamescatchingfire',
 'home',
 'salt',
 'noah',
 'theadventuresoftintin',
 'megamind',
 'harrypotterandthephilosophersstone',
 'ripd',
 'piratesofthecaribbeanthecurseoftheblackpearl',
 'thehungergamesmockingjaypart1',
 'thedavincicode',
 'rio2',
 'fastfive',
 'sherlockholmesagameofshadows',
 'clashofthetitans',
 'thebournelegacy',
 'howthegrinchstolechristmas',
 'thedayaftertomorrow',
 'missionimpossibleii',
 'lifeofpi',
 'ghostrider',
 'jasonbourne',
 'prometheus',
 'robocop',
 'speedracer',
 'howdoyouknow',
 'knightandday',
 'oblivion',
 'starwarsepisodeiiirevengeofthesith',
 'starwarsepisodeiiattackoftheclones',
 'monstersinc',
 'thewolverine',
 'starwarsepisodeithephantommenace',
 'thecroods',
 'thehuntsmanwinterswar',
 'teenagemutantninjaturtles',
 'gravity',
 'teenagemutantninjaturtlesoutoftheshadows',
 'fantasticfour',
 'sanandreas',
 'tomorrowneverdies',
 'oceanstwelve',
 'insurgent',
 'thegreenhornet',
 '300riseofanempire',
 'thesmurfs',
 'homeontherange',
 'allegiant',
 'realsteel',
 'thesmurfs2',
 'endersgame',
 'thelordoftheringsthefellowshipofthering',
 'kingdomofheaven',
 'theprincessandthefrog',
 'themartian',
 'theisland',
 'casinoroyale',
 'publicenemies',
 'americangangster',
 'thetakingofpelham123',
 'littlefockers',
 'theotherguys',
 'eraser',
 'djangounchained',
 'theexpendables2',
 'eragon',
 'wherethewildthingsare',
 'thetourist',
 'endofdays',
 'thewolfofwallstreet',
 'cloudatlas',
 'legendoftheguardianstheowlsofgahoole',
 'theexpendables3',
 'pointbreak',
 'intheheartofthesea',
 'greenzone',
 'thepeanutsmovie',
 'gangsofnewyork',
 'surfsup',
 'sexandthecity2',
 'iceagecontinentaldrift',
 'cinderella',
 'thelovelybones',
 'findingnemo',
 'thelordoftheringsthereturnoftheking',
 'thelordoftheringsthetwotowers',
 'seventhson',
 'riseoftheplanetoftheapes',
 'agooddaytodiehard',
 'theincredibles',
 'meninblack',
 'toystory2',
 'cloudywithachanceofmeatballs',
 'iceagedawnofthedinosaurs',
 'thedeparted',
 'tropicthunder',
 'thegirlwiththedragontattoo',
 'sherlockholmes',
 'benhur',
 'atlantisthelostempire',
 'alvinandthechipmunkstheroadchip',
 'youdontmesswiththezohan',
 'pixels',
 'contact',
 'theinterpreter',
 'percyjacksonseaofmonsters',
 'nowyouseeme2',
 'rio',
 'cinderellaman',
 'seabiscuit',
 'happyfeet',
 'thebournesupremacy',
 'oceanseleven',
 'thethreemusketeers',
 'hoteltransylvania',
 'enchanted',
 'safehouse',
 'towerheist',
 'theholiday',
 'itscomplicated',
 'oceansthirteen',
 'openseason',
 'divergent',
 'therundown',
 'memoirsofageisha',
 'thefastandthefurioustokyodrift',
 'arthurchristmas',
 'meetjoeblack',
 'collateraldamage',
 'scottpilgrimvstheworld',
 'dredd',
 'catsdogs2therevengeofkittygalore',
 'jumper',
 'brucealmighty',
 'theexpendables',
 'missionimpossible',
 'thehungergames',
 'thehangoverpartii',
 'red2',
 'alvinandthechipmunkschipwrecked',
 'grownups2',
 'getsmart',
 'shutterisland',
 'justgowithit',
 'spacejam',
 'yogibear',
 'zookeeper',
 'thetimemachine',
 'thelegendofzorro',
 'marsattacks',
 'surrogates',
 'walkingwithdinosaurs',
 'nine',
 'thelastwitchhunter',
 'oceans',
 'asoundofthunder',
 'abeautifulmind',
 'thelionking',
 'journey2themysteriousisland',
 'jackandjill',
 'thelittleprince',
 'thesecretlifeofpets',
 'despicableme2',
 'childrenofmen',
 'wanted',
 'iceagethemeltdown',
 'hairspray',
 'grownups',
 'theterminal',
 'verticallimit',
 'charliewilsonswar',
 'dreamgirls',
 'killers',
 'monsterhouse',
 'immortals',
 'soldier',
 'minions',
 'suckerpunch',
 'sphere',
 'theangrybirdsmovie',
 'foolsgold',
 'funnypeople',
 'thekingdom',
 'talladeganightstheballadofrickybobby',
 'thesimpsonsmovie',
 'shrek2',
 'cars',
 'xxx',
 'thespongebobmoviespongeoutofwater',
 'inglouriousbasterds',
 'swat',
 'avpalienvspredator',
 'alvinandthechipmunksthesqueakquel',
 'battlelosangeles',
 'warhorse',
 'themonumentsmen',
 'wallstreetmoneyneversleeps',
 'stardust',
 'thedilemma',
 'underworldawakening',
 'rockofages',
 'osmosisjones',
 'legendsofozdorothysreturn',
 'blackhat',
 'skycaptainandtheworldoftomorrow',
 'escapeplan',
 'thesumofallfears',
 'thetwilightsagaeclipse',
 'despicableme',
 'agora',
 'hallpass',
 'thefinesthours',
 'bodyoflies',
 'dinnerforschmucks',
 'entrapment',
 'iceage',
 'dreamcatcher',
 'thematrix',
 'lesmisrables',
 'youvegotmail',
 'duedate',
 'unbroken',
 'spacecowboys',
 'thekid',
 'thedictator',
 'eyeswideshut',
 'focus',
 'thismeanswar',
 'bladetrinity',
 'residentevilretribution',
 'deathrace',
 'fightclub',
 'ifrankenstein',
 'elektra',
 'sincityadametokillfor',
 'everest',
 'perfumethestoryofamurderer',
 'austinpowersingoldmember',
 'astroboy',
 'jurassicpark',
 'littleman',
 'u571',
 'theloveguru',
 'thehatefuleight',
 'hop',
 '300',
 'meetthefockers',
 'marleyme',
 'thegreenmile',
 'wildhogs',
 'chickenlittle',
 'gonegirl',
 'thebourneidentity',
 'goldeneye',
 '2guns',
 'catsdogs',
 'theitalianjob',
 'couplesretreat',
 'mazerunnerthescorchtrials',
 'eatpraylove',
 'thescorpionking',
 'jackreacher',
 'thisisit',
 'contagion',
 'coraline',
 'thehappening',
 'theshaggydog',
 'hellboy',
 'paranorman',
 'thetaleofdespereaux',
 'londonhasfallen',
 'shooter',
 'thelegomovie',
 'gangstersquad',
 'invictus',
 'stateofplay',
 'duplicity',
 'planet51',
 'troublewiththecurve',
 'righteouskill',
 'thesoloist',
 'xxxstateoftheunion',
 'priest',
 'winterstale',
 'themortalinstrumentscityofbones',
 'meetdave',
 'inkheart',
 'thespirit',
 'mortdecai',
 'inthenameofthekingadungeonsiegetale',
 'deadpool',
 'americansniper',
 'goosebumps',
 'theflintstonesinvivarockvegas',
 'leatherheads',
 'theinternship',
 'residentevilafterlife',
 'redtails',
 'thatsmyboy',
 'afterthesunset',
 'ghostriderspiritofvengeance',
 'thepacifier',
 'alvinandthechipmunks',
 'captainphillips',
 'datenight',
 'killbillvol1',
 'theforbiddenkingdom',
 'evita',
 'paddington',
 'semipro',
 'changeling',
 'imaginethat',
 'burlesque',
 'bladeii',
 'sevenpounds',
 'thegodfatherpartiii',
 'youmeanddupree',
 'gigli',
 'allthekingsmen',
 'luckyyou',
 'catchmeifyoucan',
 'zerodarkthirty',
 'thebreakup',
 'valentinesday',
 'thedukesofhazzard',
 'thechangeup',
 'manonthemoon',
 'frompariswithlove',
 'thetwilightsaganewmoon',
 'shrek',
 'theadjustmentbureau',
 'ted',
 'super8',
 'erinbrockovich',
 '22jumpstreet',
 'centralintelligence',
 'daddyshome',
 'intothewoods',
 'insideman',
 'weboughtazoo',
 'knowing',
 'crazystupidlove',
 'moneyball',
 'vforvendetta',
 'hanselgretelwitchhunters',
 'iamnumberfour',
 'syriana',
 '13hoursthesecretsoldiersofbenghazi',
 'silenthill',
 'americanreunion',
 'thejudge',
 'theadventuresofsharkboyandlavagirl',
 'ninjaassassin',
 'marmaduke',
 'hereafter',
 'hannibalrising',
 'thehost',
 'theinternational',
 'escapefromla',
 'theirongiant',
 'freestateofjones',
 'easternpromises',
 'yourhighness',
 'fairgame',
 'gamer',
 'zoolander2',
 'driveangry',
 'theboatthatrocked',
 'indianajonesandthelastcrusade',
 'chappie',
 'kpax',
 '310toyuma',
 'taken3',
 'happilyneverafter',
 'startrekfirstcontact',
 'jonahhex',
 'theinfiltrator',
 'thebucketlist',
 'prisoners',
 'themuppets',
 'blade',
 'loveactually',
 'abugslife',
 'residentevilextinction',
 'savages',
 'cellular',
 'theantbully',
 'acrosstheuniverse',
 'babylonad',
 'aliensintheattic',
 'alltheprettyhorses',
 'curseofthegoldenflower',
 'bangkokdangerous',
 'loveinthetimeofcholera',
 'johnnyenglishreborn',
 'foodfight',
 'argo',
 'thebountyhunter',
 'underworldevolution',
 'victorfrankenstein',
 'unleashed',
 'thesweetestthing',
 'themechanic',
 '21jumpstreet',
 'nottinghill',
 'alongcamepolly',
 'licencetokill',
 'redridinghood',
 'oneforthemoney',
 'thewarriorsway',
 '8mile',
 'whyididnoteatmyfather',
 'manonaledge',
 'americanhustle',
 'theproposal',
 'backtothefuturepartii',
 'lucy',
 'fiftyshadesofgrey',
 'lonesurvivor',
 'theconjuring2',
 'thesocialnetwork',
 'hesjustnotthatintoyou',
 'backtothefuturepartiii',
 'juliejulia',
 'thetalentedmrripley',
 'theintern',
 'ridealong2',
 'sincity',
 'vantagepoint',
 'iloveyouman',
 '17again',
 'thefinaldestination',
 'gethimtothegreek',
 'shallwedance',
 'thelincolnlawyer',
 'unknown',
 'theprestige',
 'escapefromplanetearth',
 'thelivingdaylights',
 'thelakehouse',
 'theoddlifeoftimothygreen',
 'gothika',
 'aliensvspredatorrequiem',
 'paul',
 'scream4',
 'finaldestination5',
 'drillbittaylor',
 'extremelyloudincrediblyclose',
 'morningglory',
 'rent',
 'thereaping',
 'colombiana',
 'marieantoinette',
 'fantasticmrfox',
 'memoirsofaninvisibleman',
 'amlie',
 'bigmiracle',
 'pandorum',
 'athousandwords',
 'disturbia',
 'thehuntingparty',
 'snowpiercer',
 'becauseisaidso',
 'frankenweenie',
 'redcliff',
 'theuglytruth',
 'waterforelephants',
 'enough',
 'angeleyes',
 'precious',
 'thething',
 'riddick',
 'cityofember',
 'the5thwave',
 'creed',
 'thetown',
 'whattoexpectwhenyoureexpecting',
 'magnolia',
 'copout',
 'howtobesingle',
 'dolphintale',
 'twilight',
 'werethemillers',
 'neversayneveragain',
 'hottubtimemachine',
 'dolphintale2',
 'amanapart',
 'therite',
 'spacechimps',
 'thehangover',
 'theblindside',
 'horriblebosses',
 'truegrit',
 'thedevilwearsprada',
 'identitythief',
 '21',
 'skyhigh',
 'secretariat',
 'friendswithbenefits',
 'neighbors2sororityrising',
 'thisis40',
 'olddogs',
 'licensetowed',
 'residentevil',
 'maxpayne',
 'intime',
 'thebackupplan',
 'somethingborrowed',
 'thepianist',
 'jedgar',
 'untraceable',
 'nannymcpheeandthebigbang',
 'ellaenchanted',
 'concussion',
 'abduction',
 'brokencity',
 'premiumrush',
 'furryvengeance',
 'walkhardthedeweycoxstory',
 'theyoungvictoria',
 'whiteout',
 'thetreeoflife',
 'punisherwarzone',
 'thewalk',
 'themazerunner',
 'thefountain',
 'exitwounds',
 'thunderandthehouseofmagic',
 'thedarkesthour',
 'thepunisher',
 'safe',
 'returnofthejedi',
 'wanderlust',
 'nacholibre',
 'bridesmaids',
 'thisistheend',
 'takers',
 'bigmommaslikefatherlikeson',
 'sourcecode',
 'thenumber23',
 'repomen',
 'thegoodgerman',
 'apocalypsenow',
 'goingthedistance',
 'moonraker',
 'extraordinarymeasures',
 'rememberthetitans',
 'thehuntforredoctober',
 'se7en',
 'district9',
 'milliondollarbaby',
 'thenotebook',
 '27dresses',
 'hannahmontanathemovie',
 'upintheair',
 'looper',
 'forgettingsarahmarshall',
 'fourbrothers',
 'babymama',
 'bridewars',
 'aviewtoakill',
 'thecurseofthewererabbit',
 'letterstojuliet',
 'thethreestooges',
 'corpsebride',
 'dragmetohell',
 'theageofadaline',
 'stepup3d',
 'strangerthanfiction',
 '30daysofnight',
 'thecabininthewoods',
 'meetthespartans',
 'hanna',
 'larrycrowne',
 'carrie',
 'sideeffects',
 'winniethepooh',
 'sanctum',
 'thefiveyearengagement',
 'thenextthreedays',
 'ultraviolet',
 'loveotherdrugs',
 'northcountry',
 'splice',
 'prideandglory',
 'alexemma',
 'frightnight',
 'thelaststand',
 'hoodwinkedtoohoodvsevil',
 'anunfinishedlife',
 'barneysversion',
 'runnerrunner',
 'antitrust',
 'thepromise',
 'theassassinationofjessejamesbythecowardrobertford',
 '1911',
 'machinegunpreacher',
 'savvaheartofthewarrior',
 'sausageparty',
 'theboss',
 'aladdin',
 'straightouttacompton',
 'indianajonesandthetempleofdoom',
 'florencefosterjenkins',
 'thebigshort',
 'takingwoodstock',
 'dawnofthedead',
 'foryoureyesonly',
 'noreservations',
 '30minutesorless',
 'alexanderandtheterriblehorriblenogoodverybadday',
 'prideprejudice',
 'bladerunner',
 'ghostsofmars',
 'ourbrandiscrisis',
 'prideandprejudiceandzombies',
 'octopussy',
 'knockedup',
 'mysisterskeeper',
 'notesonascandal',
 'rendition',
 'joyfulnoise',
 'aboutaboy',
 'anonymous',
 'theduchess',
 'returntooz',
 'case39',
 'mindhunters',
 'whatjusthappened',
 'paulblartmallcop',
 'the40yearoldvirgin',
 'pineappleexpress',
 'legion',
 'paingain',
 'agentcodybanks2destinationlondon',
 'selfless',
 'thepassionofthechrist',
 'grantorino',
 'w',
 'schindlerslist',
 'thehelp',
 'cloverfield',
 'nostringsattached',
 'bridgetoterabithia',
 'amadeachristmas',
 'thegrey',
 'goodfellas',
 'contraband',
 'thehousebunny',
 'milliondollararm',
 'thegiver',
 'goodluckchuck',
 'augustrush',
 'thegambler',
 'eddietheeagle',
 'thelosers',
 'dontbeafraidofthedark',
 'thebox',
 'legend',
 'sharknight',
 'theconspirator',
 'bigtroubleinlittlechina',
 'warrior',
 'stoploss',
 'thepossession',
 'strawdogs',
 'theroad',
 'bloodrayne',
 'carnage',
 'thebestoffer',
 'littlewhitelies',
 'ontheroad',
 'rockybalboa',
 'oldschool',
 'zackandmirimakeaporno',
 'themenwhostareatgoats',
 'readytorumble',
 'idontknowhowshedoesit',
 'piranha3d',
 'faster',
 'zombieland',
 'theempirestrikesback',
 'theidesofmarch',
 'pitchblack',
 'her',
 'anywherebuthere',
 'haywire',
 'harleydavidsonandthemarlboroman',
 'inthevalleyofelah',
 'cocobeforechanel',
 'bodyguardsandassassins',
 '1408',
 'spaceballs',
 'thewaterdiviner',
 'theressomethingaboutmary',
 'thegameplan',
 'underworld',
 'derailed',
 'theinformant',
 'hailcaesar',
 'thetransporterrefueled',
 'hitrun',
 'stone',
 'michaelclayton',
 'deathatafuneral',
 'silverliningsplaybook',
 'freedomwriters',
 'forcoloredgirls',
 'neverbackdown',
 'tinkertailorsoldierspy',
 'thebeaver',
 'raidersofthelostark',
 'pulse',
 'theconjuring',
 'schoolofrock',
 'thedescendants',
 'whydidigetmarriedtoo',
 'mebeforeyou',
 'madeaswitnessprotection',
 'badmoms',
 'boogeyman',
 'spotlight',
 'thegrudge2',
 'vampiressuck',
 'teamamericaworldpolice',
 'milk',
 'averyharoldkumarchristmas',
 'thestepfather',
 'thedebt',
 'onemissedcall',
 'eternalsunshineofthespotlessmind',
 'daybreakers',
 'shesoutofmyleague',
 'alphaandomega',
 'nerve',
 'vampires',
 'mybestfriendsgirl',
 'reignoverme',
 'intothewild',
 'fromdusktilldawn',
 'thecountrybears',
 'thekiterunner',
 '21grams',
 'capitalismalovestory',
 'secretintheireyes',
 'disastermovie',
 'whatsyournumber',
 'lockout',
 'crankhighvoltage',
 'onenightwiththeking',
 '12rounds',
 'letmein',
 'triple9',
 'burnt',
 'everybodysfine',
 'superbabiesbabygeniuses2',
 'inherentvice',
 'doogal',
 'anamericancarol',
 'littleboy',
 'adangerousmethod',
 'ascannerdarkly',
 'bandslam',
 'amostviolentyear',
 'flashofgenius',
 'imnotthere',
 'thebrothersbloom',
 'myallamerican',
 'thechildrenofhuangshi',
 'theyards',
 'dylandogdeadofnight',
 'zambezia',
 'survivor',
 'badteacher',
 'acinderellastory',
 'backtothefuture',
 'fightvalley',
 'theswitch',
 'spiritedaway',
 'thebookthief',
 'sexdrive',
 'leapyear',
 'takemehometonight',
 'adaptation',
 'theinventionoflying',
 'boratculturallearningsofamericaformakebenefitgloriousnationofkazakhstan',
 'leftbehind',
 'badsanta',
 'diaryofawimpykidrodrickrules',
 'promnight',
 'meangirls',
 'thefog',
 'soulsurfer',
 'lovehappens',
 'lovethecoopers',
 'stevejobs',
 'iloveyoubethcooper',
 'youthinrevolt',
 'getaway',
 'thelaststation',
 'rocknrolla',
 'maoslastdancer',
 'midnightspecial',
 'theinformers',
 'superbad',
 'hoodwinked',
 'hotelrwanda',
 'hitman',
 'blacknativity',
 'sideways',
 'halloween',
 'goodboy',
 'smokinaces',
 'sawthefinalchapter',
 'beastly',
 'thehillshaveeyes',
 'pitchperfect',
 'evildead',
 'mylifeinruins',
 'runningscared',
 'roar',
 'southlandtales',
 'theapparition',
 'furanimaginaryportraitofdianearbus',
 'becomingjane',
 'theartist',
 'theunborn',
 'moonrisekingdom',
 'panslabyrinth',
 'theroommate',
 'hotfuzz',
 'rememberme',
 'thingswelostinthefire',
 'homealone',
 'americanbeauty',
 'thekingsspeech',
 'theimitationgame',
 'diaryofawimpykid',
 'mama',
 'thequeen',
 'thewomaninblack',
 'whenastrangercalls',
 'thelizziemcguiremovie',
 'krampus',
 'copland',
 'thetheoryofeverything',
 'halloweenii',
 'thelasthouseontheleft',
 'theweddingdate',
 'drive',
 'allaboutsteve',
 'ramonaandbeezus',
 'keanu',
 'countrystrong',
 'theplacebeyondthepines',
 'thenovemberman',
 'thehurtlocker',
 'killingthemsoftly',
 'u23d',
 'oneday',
 'knockaroundguys',
 'raiseyourvoice',
 ...]

In [530]:
# Our Agenda is to first find the index of the Movie with title.
closest_match_title = find_close_match[0][0]
# closest_match_title
index_of_the_movie = df_new[df_new["clean_title"] == closest_match_title].index[0]
index_of_the_movie

np.int64(68)

In [531]:
# In the similarity_score array we have bruteforce array with all combinations
# of solutions we get list of all movies from the index.
similarity_score = list(enumerate(similarity[index_of_the_movie]))

In [532]:
# So in the below code we are basically sorting in descending order
# to find the Highest Recommended movies
sorted_similar_score = sorted(similarity_score , key= lambda x : x[1] , reverse=True)
sorted_similar_score

[(68, np.float64(0.9999999999999996)),
 (127, np.float64(0.4574447205785295)),
 (23, np.float64(0.4280933486795169)),
 (27, np.float64(0.40597241736665374)),
 (7, np.float64(0.3863958269476032)),
 (14, np.float64(0.3817148409929318)),
 (137, np.float64(0.36759581235874367)),
 (100, np.float64(0.3508724993375327)),
 (428, np.float64(0.31692699907846444)),
 (64, np.float64(0.3056598768802264)),
 (176, np.float64(0.30413390246226585)),
 (169, np.float64(0.3016162850106335)),
 (40, np.float64(0.2844912156790806)),
 (102, np.float64(0.2780406009776234)),
 (56, np.float64(0.27372051221603927)),
 (13, np.float64(0.24655905358853653)),
 (314, np.float64(0.24090158393312155)),
 (9, np.float64(0.2382552128851246)),
 (80, np.float64(0.22832791234824443)),
 (285, np.float64(0.22618371458132558)),
 (1114, np.float64(0.22618371458132558)),
 (59, np.float64(0.2208885145092328)),
 (15, np.float64(0.22000654012515564)),
 (53, np.float64(0.21900143993920138)),
 (175, np.float64(0.2176078175211597)),
 (73, np.float64(0.21737779694721493)),
 (434, np.float64(0.2157341617723467)),
 (98, np.float64(0.21138916352972575)),
 (75, np.float64(0.20980710681594944)),
 (142, np.float64(0.2081918281941747)),
 (87, np.float64(0.20792941844478613)),
 (4, np.float64(0.20678804748029556)),
 (173, np.float64(0.2029038780335466)),
 (49, np.float64(0.19772013984146292)),
 (862, np.float64(0.19458788576341687)),
 (423, np.float64(0.19411529175187453)),
 (747, np.float64(0.19389618322112154)),
 (32, np.float64(0.1934968085783109)),
 (227, np.float64(0.19085742049646587)),
 (325, np.float64(0.18652098644670834)),
 (104, np.float64(0.18514442898794703)),
 (81, np.float64(0.18508999875628776)),
 (160, np.float64(0.18135042137811125)),
 (293, np.float64(0.17701675642253906)),
 (26, np.float64(0.17590618961664628)),
 (0, np.float64(0.17590082654130496)),
 (218, np.float64(0.17520115195136116)),
 (24, np.float64(0.17404469606598547)),
 (383, np.float64(0.1737591426397536)),
 (387, np.float64(0.17313584026611095)),
 (526, np.float64(0.1704923897625215)),
 (1016, np.float64(0.17034314359769048)),
 (909, np.float64(0.16876410912696327)),
 (342, np.float64(0.1680166367978207)),
 (155, np.float64(0.1669015131983939)),
 (228, np.float64(0.1669015131983939)),
 (296, np.float64(0.16623008001845846)),
 (269, np.float64(0.16493403957361844)),
 (594, np.float64(0.16289919622476898)),
 (103, np.float64(0.1622047479798751)),
 (532, np.float64(0.1612619768205211)),
 (793, np.float64(0.16093253423574608)),
 (419, np.float64(0.16029264090937534)),
 (366, np.float64(0.15827338129496404)),
 (99, np.float64(0.15802635801803744)),
 (34, np.float64(0.1577599364543104)),
 (705, np.float64(0.15770710620118383)),
 (240, np.float64(0.15752080122628032)),
 (1104, np.float64(0.15728351551716843)),
 (1033, np.float64(0.15507233384355743)),
 (435, np.float64(0.153301007957441)),
 (238, np.float64(0.15330100795744098)),
 (125, np.float64(0.15235953943417763)),
 (737, np.float64(0.1517286483621763)),
 (1407, np.float64(0.149709181280246)),
 (1323, np.float64(0.14898867914768985)),
 (512, np.float64(0.14896132831643122)),
 (35, np.float64(0.1487228140952827)),
 (101, np.float64(0.1482132217352749)),
 (422, np.float64(0.1471654642261943)),
 (1042, np.float64(0.14691063206231755)),
 (245, np.float64(0.14623517730259278)),
 (165, np.float64(0.1459409143225626)),
 (1267, np.float64(0.14426337681843782)),
 (55, np.float64(0.14355223097933387)),
 (69, np.float64(0.14295392702840035)),
 (405, np.float64(0.1422456078395403)),
 (25, np.float64(0.14148769414553325)),
 (406, np.float64(0.14039323057009676)),
 (523, np.float64(0.13892028878812532)),
 (183, np.float64(0.13874893028107768)),
 (82, np.float64(0.13870091196149423)),
 (91, np.float64(0.1380399443975216)),
 (111, np.float64(0.1370880328923582)),
 (682, np.float64(0.1370880328923582)),
 (213, np.float64(0.136766355406668)),
 (11, np.float64(0.13640309751308247)),
 (190, np.float64(0.13572629198241362)),
 (767, np.float64(0.13481444187185865)),
 (18, np.float64(0.1344598433878723)),
 (307, np.float64(0.13445387839692433)),
 (274, np.float64(0.13437314955242213)),
 (425, np.float64(0.13411044519645504)),
 (107, np.float64(0.13364719529685967)),
 (237, np.float64(0.13364719529685967)),
 (171, np.float64(0.1333918995617474)),
 (478, np.float64(0.13276256731690428)),
 (1129, np.float64(0.13140086396352085)),
 (5, np.float64(0.13119603006819427)),
 (663, np.float64(0.13113351706608986)),
 (208, np.float64(0.1305872284998378)),
 (670, np.float64(0.1305872284998378)),
 (291, np.float64(0.1305335220494891)),
 (202, np.float64(0.1303193569798152)),
 (199, np.float64(0.12956299912940142)),
 (209, np.float64(0.12938490557562543)),
 (267, np.float64(0.12926412214741437)),
 (203, np.float64(0.12926412214741434)),
 (313, np.float64(0.1290549069794425)),
 (43, np.float64(0.1285200308365858)),
 (904, np.float64(0.12815848068746333)),
 (51, np.float64(0.1269662828618147)),
 (97, np.float64(0.126245866529232)),
 (324, np.float64(0.12536180787427653)),
 (496, np.float64(0.12485002994000116)),
 (71, np.float64(0.12448010311224698)),
 (360, np.float64(0.12357990504920377)),
 (180, np.float64(0.12357990504920376)),
 (235, np.float64(0.12327952679426826)),
 (192, np.float64(0.12313433273165239)),
 (754, np.float64(0.12250992902212134)),
 (1304, np.float64(0.12250992902212134)),
 (735, np.float64(0.12242552671859797)),
 (1437, np.float64(0.12223703464880996)),
 (126, np.float64(0.12176683727565484)),
 (109, np.float64(0.12119508818627768)),
 (86, np.float64(0.11995202878081346)),
 (2, np.float64(0.1194594105648306)),
 (438, np.float64(0.11912760644256229)),
 (636, np.float64(0.11912760644256229)),
 (212, np.float64(0.11885655351696293)),
 (400, np.float64(0.11812059254900927)),
 (424, np.float64(0.11762264143238677)),
 (301, np.float64(0.11757650585836937)),
 (885, np.float64(0.11752850564985401)),
 (117, np.float64(0.11723578164450808)),
 (47, np.float64(0.11641283923332396)),
 (649, np.float64(0.11622905250359437)),
 (1178, np.float64(0.11572537765179601)),
 (643, np.float64(0.11533674824085335)),
 (888, np.float64(0.11451445229787954)),
 (738, np.float64(0.1142544216682036)),
 (88, np.float64(0.11398504727298843)),
 (367, np.float64(0.11388549409616847)),
 (289, np.float64(0.1137292107787456)),
 (916, np.float64(0.11372921077874559)),
 (1309, np.float64(0.11372921077874559)),
 (581, np.float64(0.11334401336131952)),
 (166, np.float64(0.1132202978286958)),
 (630, np.float64(0.1130918572906628)),
 (1422, np.float64(0.11255277148284906)),
 (270, np.float64(0.11240015748521985)),
 (268, np.float64(0.11124663426282361)),
 (66, np.float64(0.11117815133195391)),
 (231, np.float64(0.11072765708699922)),
 (462, np.float64(0.11072765708699922)),
 (42, np.float64(0.11042479306102604)),
 (300, np.float64(0.11018297404673816)),
 (495, np.float64(0.11018297404673816)),
 (655, np.float64(0.11007553084805224)),
 (244, np.float64(0.109178184011343)),
 (251, np.float64(0.10905286238742484)),
 (161, np.float64(0.10864690015770634)),
 (172, np.float64(0.108599464149846)),
 (260, np.float64(0.10859946414984598)),
 (188, np.float64(0.1084599563123384)),
 (1059, np.float64(0.10795682590273209)),
 (31, np.float64(0.1077344635123662)),
 (610, np.float64(0.1077344635123662)),
 (685, np.float64(0.10728835615716403)),
 (872, np.float64(0.1070984090807924)),
 (799, np.float64(0.10686176060625024)),
 (693, np.float64(0.10676765071515795)),
 (772, np.float64(0.1066374602236567)),
 (470, np.float64(0.10602361620999637)),
 (58, np.float64(0.10586037728914807)),
 (210, np.float64(0.10565738500785496)),
 (402, np.float64(0.10520488877436)),
 (763, np.float64(0.10495802518321175)),
 (1340, np.float64(0.10485693874428818)),
 (599, np.float64(0.1046584895868848)),
 (805, np.float64(0.1036227702481713)),
 (151, np.float64(0.10347807931851019)),
 (665, np.float64(0.10303347769478487)),
 (507, np.float64(0.10293279475195458)),
 (182, np.float64(0.10241091321754647)),
 (123, np.float64(0.1022954338575129)),
 (147, np.float64(0.10137796748742195)),
 (1329, np.float64(0.10060882093663223)),
 (63, np.float64(0.10059511432396628)),
 (33, np.float64(0.0999600239840112)),
 (395, np.float64(0.0999600239840112)),
 (331, np.float64(0.09980612085349731)),
 (1142, np.float64(0.09895537512932993)),
 (143, np.float64(0.09886006992073144)),
 (575, np.float64(0.09859996028394401)),
 (1293, np.float64(0.09859996028394401)),
 (124, np.float64(0.09855064797264063)),
 (1120, np.float64(0.09834765981073369)),
 (170, np.float64(0.09794042137487838)),
 (825, np.float64(0.09794042137487836)),
 (524, np.float64(0.09794042137487835)),
 (221, np.float64(0.09693587767771096)),
 (298, np.float64(0.0963385941279287)),
 (1315, np.float64(0.09617558454562519)),
 (44, np.float64(0.09542871024823295)),
 (132, np.float64(0.09522471214636104)),
 (804, np.float64(0.09501616525791179)),
 (29, np.float64(0.09468439989692401)),
 (149, np.float64(0.09468439989692401)),
 (16, np.float64(0.09424321440888564)),
 (1018, np.float64(0.09409811314590939)),
 (272, np.float64(0.09409811314590938)),
 (130, np.float64(0.09396435598782482)),
 (128, np.float64(0.09366679790434988)),
 (162, np.float64(0.09366679790434987)),
 (1328, np.float64(0.0932061677727006)),
 (54, np.float64(0.09319056275524501)),
 (923, np.float64(0.09257221449397351)),
 (483, np.float64(0.09238154031729023)),
 (1080, np.float64(0.09238154031729023)),
 (92, np.float64(0.09199900641609601)),
 (676, np.float64(0.09199900641609601)),
 (193, np.float64(0.09146256448784748)),
 (62, np.float64(0.09105224021837041)),
 (119, np.float64(0.09041724370633415)),
 (12, np.float64(0.08990784673056329)),
 (1182, np.float64(0.08990784673056329)),
 (1186, np.float64(0.08977871959363849)),
 (84, np.float64(0.08950850462532378)),
 (138, np.float64(0.08925529759858894)),
 (444, np.float64(0.08891435936589072)),
 (959, np.float64(0.0889126689627619)),
 (714, np.float64(0.08859044441175695)),
 (899, np.float64(0.08855718349659485)),
 (19, np.float64(0.08850837821126953)),
 (1092, np.float64(0.08816095250015644)),
 (642, np.float64(0.08727792082419236)),
 (371, np.float64(0.08727792082419235)),
 (1001, np.float64(0.08727792082419235)),
 (1217, np.float64(0.08727792082419235)),
 (654, np.float64(0.08660474971146406)),
 (368, np.float64(0.08643463611230848)),
 (678, np.float64(0.08617608143160957)),
 (398, np.float64(0.08602205792791848)),
 (243, np.float64(0.08569786870301857)),
 (641, np.float64(0.08548940848500017)),
 (468, np.float64(0.08524619488126076)),
 (598, np.float64(0.08524619488126076)),
 (373, np.float64(0.08481889296799709)),
 (924, np.float64(0.08481889296799709)),
 (961, np.float64(0.08481889296799709)),
 (1017, np.float64(0.08481889296799709)),
 (121, np.float64(0.0839664201465694)),
 (829, np.float64(0.08379074717799256)),
 (878, np.float64(0.08379074717799256)),
 (294, np.float64(0.08357453858285102)),
 (17, np.float64(0.08311894313163432)),
 (709, np.float64(0.08233584900267071)),
 (918, np.float64(0.08231630803906274)),
 (1346, np.float64(0.08228641288353201)),
 (326, np.float64(0.08184185850784947)),
 (141, np.float64(0.08161701781239863)),
 (554, np.float64(0.08155539680111303)),
 (751, np.float64(0.08110237398993755)),
 (288, np.float64(0.08046626711787301)),
 (415, np.float64(0.08046626711787301)),
 (1, np.float64(0.07958682795686245)),
 (185, np.float64(0.07947891356423485)),
 (1175, np.float64(0.07947891356423485)),
 (1145, np.float64(0.07941840429504154)),
 (545, np.float64(0.07875236506747693)),
 (346, np.float64(0.07873560746220849)),
 (1381, np.float64(0.07852703595022845)),
 (818, np.float64(0.07835233709990268)),
 (576, np.float64(0.07829627719111583)),
 (303, np.float64(0.07791112811974994)),
 (527, np.float64(0.07775335170335965)),
 (611, np.float64(0.07760855948888264)),
 (95, np.float64(0.07748208233909364)),
 (61, np.float64(0.07683078765538531)),
 (779, np.float64(0.07679141753358146)),
 (1097, np.float64(0.07672157539313468)),
 (1109, np.float64(0.07672157539313468)),
 (1139, np.float64(0.07672157539313468)),
 (1352, np.float64(0.07672157539313468)),
 (1364, np.float64(0.07672157539313468)),
 (339, np.float64(0.0766505039787205)),
 (381, np.float64(0.07665050397872047)),
 (533, np.float64(0.07586432418108816)),
 (1347, np.float64(0.07586432418108816)),
 (1118, np.float64(0.07540407125265838)),
 (329, np.float64(0.07540407125265837)),
 (375, np.float64(0.07526459679662087)),
 (1192, np.float64(0.07521708472456592)),
 (1210, np.float64(0.0749334383234799)),
 (286, np.float64(0.07448066415821561)),
 (115, np.float64(0.07423264260982634)),
 (194, np.float64(0.07414505244054859)),
 (1446, np.float64(0.07345531603115878)),
 (39, np.float64(0.07317005159027798)),
 (178, np.float64(0.07317005159027798)),
 (988, np.float64(0.07273160068682696)),
 (1472, np.float64(0.07270190825828322)),
 (164, np.float64(0.07253593917371991)),
 (214, np.float64(0.07233379496506731)),
 (85, np.float64(0.07155843342917081)),
 (112, np.float64(0.07155843342917081)),
 (1022, np.float64(0.07147696351420017)),
 (93, np.float64(0.07147696351420016)),
 (1271, np.float64(0.07074384707276662)),
 (1128, np.float64(0.07074384707276661)),
 (1011, np.float64(0.07057358485943205)),
 (28, np.float64(0.0703624758466585)),
 (388, np.float64(0.0703624758466585)),
 (1020, np.float64(0.07027390798611546)),
 (669, np.float64(0.06998720663307421)),
 (30, np.float64(0.06997201678880784)),
 (328, np.float64(0.06997201678880784)),
 (321, np.float64(0.06990462582952545)),
 (1012, np.float64(0.06990462582952545)),
 (283, np.float64(0.06961787842639419)),
 (72, np.float64(0.06954229716599748)),
 (539, np.float64(0.06925433610644438)),
 (812, np.float64(0.06925433610644438)),
 (489, np.float64(0.06879720678003265)),
 (617, np.float64(0.06879720678003265)),
 (21, np.float64(0.06862186316796973)),
 (658, np.float64(0.06855829496241485)),
 (1100, np.float64(0.06834901173682291)),
 (864, np.float64(0.0681969559050086)),
 (1236, np.float64(0.0681969559050086)),
 (675, np.float64(0.06810576001719588)),
 (1013, np.float64(0.06800640801679173)),
 (146, np.float64(0.06800640801679171)),
 (1493, np.float64(0.06790946369378331)),
 (745, np.float64(0.06785511437439767)),
 (787, np.float64(0.06740722093592932)),
 (536, np.float64(0.06722693919846215)),
 (74, np.float64(0.06721098406848822)),
 (330, np.float64(0.06685963086628081)),
 (583, np.float64(0.06682359764842982)),
 (726, np.float64(0.06682359764842982)),
 (77, np.float64(0.06638128365845214)),
 (472, np.float64(0.06638128365845214)),
 (1389, np.float64(0.06625487583661561)),
 (662, np.float64(0.06621981106790575)),
 (380, np.float64(0.06597025008621996)),
 (821, np.float64(0.06597025008621996)),
 (699, np.float64(0.06559801503409715)),
 (951, np.float64(0.06543919662519036)),
 (619, np.float64(0.0652936142499189)),
 (1140, np.float64(0.06524530228307468)),
 (355, np.float64(0.06517058113843865)),
 (316, np.float64(0.06515967848990759)),
 (351, np.float64(0.06515967848990759)),
 (822, np.float64(0.06478149956470072)),
 (1358, np.float64(0.06478149956470072)),
 (186, np.float64(0.06463206107370717)),
 (521, np.float64(0.06463206107370717)),
 (895, np.float64(0.06411705636375013)),
 (970, np.float64(0.06411705636375013)),
 (1477, np.float64(0.06361416972599783)),
 (1160, np.float64(0.06355213736631392)),
 (3, np.float64(0.06339443100471297)),
 (136, np.float64(0.06339443100471297)),
 (292, np.float64(0.06300189205398155)),
 (1246, np.float64(0.06300189205398155)),
 (482, np.float64(0.06293549271139429)),
 (118, np.float64(0.06264290399188321)),
 (1056, np.float64(0.06264290399188321)),
 (1206, np.float64(0.06264290399188321)),
 (715, np.float64(0.06258487442501234)),
 (215, np.float64(0.06246569598765818)),
 (451, np.float64(0.062465695987658165)),
 (167, np.float64(0.06220268136268772)),
 (565, np.float64(0.06217366214890278)),
 (502, np.float64(0.06217366214890277)),
 (592, np.float64(0.06194296130825108)),
 (660, np.float64(0.061714809662649014)),
 (1348, np.float64(0.061714809662649014)),
 (621, np.float64(0.0615671663658262)),
 (1066, np.float64(0.061567166365826195)),
 (10, np.float64(0.06126596872645729)),
 (544, np.float64(0.06126596872645729)),
 (1209, np.float64(0.06121276335929898)),
 (52, np.float64(0.06093569155637525)),
 (391, np.float64(0.060826780492453165)),
 (275, np.float64(0.060584923548569355)),
 (661, np.float64(0.060584923548569355)),
 (461, np.float64(0.06045014045937041)),
 (114, np.float64(0.06039690386563594)),
 (377, np.float64(0.06039690386563594)),
 (710, np.float64(0.05997601439040673)),
 (344, np.float64(0.05997601439040672)),
 (410, np.float64(0.059976014390406715)),
 (1276, np.float64(0.059976014390406715)),
 (1413, np.float64(0.059976014390406715)),
 (989, np.float64(0.05997601439040671)),
 (168, np.float64(0.059563803221281145)),
 (1153, np.float64(0.05938510328619487)),
 (901, np.float64(0.059373225077597964)),
 (908, np.float64(0.0591599761703664)),
 (1199, np.float64(0.05906029627450463)),
 (634, np.float64(0.05881132071619338)),
 (602, np.float64(0.058811320716193376)),
 (794, np.float64(0.05881132071619337)),
 (1442, np.float64(0.0587882529291847)),
 (233, np.float64(0.05876425282492701)),
 (1283, np.float64(0.05876425282492701)),
 (739, np.float64(0.05872077205476722)),
 (733, np.float64(0.058502177007995725)),
 (547, np.float64(0.05837636572902505)),
 (695, np.float64(0.05825385485793788)),
 (134, np.float64(0.058220237164540105)),
 (1076, np.float64(0.0582202371645401)),
 (1368, np.float64(0.058185280549461565)),
 (407, np.float64(0.05799605962380769)),
 (1402, np.float64(0.05725722614893976)),
 (57, np.float64(0.057217003294555854)),
 (430, np.float64(0.057184885973308106)),
 (177, np.float64(0.056672006680659755)),
 (819, np.float64(0.056610148914347895)),
 (520, np.float64(0.056545928645331395)),
 (668, np.float64(0.056545928645331395)),
 (1307, np.float64(0.056545928645331395)),
 (1045, np.float64(0.05654592864533139)),
 (466, np.float64(0.05620007874260993)),
 (261, np.float64(0.055860498118661714)),
 (968, np.float64(0.055860498118661714)),
 (1288, np.float64(0.055853631853732724)),
 (408, np.float64(0.05577656043320085)),
 (828, np.float64(0.055686331373691514)),
 (1232, np.float64(0.055686331373691514)),
 (1247, np.float64(0.055686331373691514)),
 (549, np.float64(0.05521239653051302)),
 (197, np.float64(0.05521239653051301)),
 (1147, np.float64(0.05521239653051301)),
 (252, np.float64(0.055199403849657616)),
 (1082, np.float64(0.05503776542402612)),
 (1243, np.float64(0.05503776542402612)),
 (698, np.float64(0.05489056600178047)),
 (265, np.float64(0.05487753869270849)),
 (46, np.float64(0.05475035998480035)),
 (113, np.float64(0.05475035998480035)),
 (1335, np.float64(0.0546574839892009)),
 (253, np.float64(0.05442734619235176)),
 (392, np.float64(0.05429973207492299)),
 (1453, np.float64(0.05429973207492299)),
 (525, np.float64(0.05425034622380049)),
 (913, np.float64(0.05398263050912935)),
 (129, np.float64(0.05364417807858202)),
 (264, np.float64(0.05364417807858202)),
 (727, np.float64(0.05364417807858202)),
 (609, np.float64(0.05364417807858201)),
 (783, np.float64(0.053057885304574955)),
 (552, np.float64(0.05260244438718)),
 (1058, np.float64(0.05260244438718)),
 (940, np.float64(0.05235135730015229)),
 (1286, np.float64(0.052351357300152286)),
 (595, np.float64(0.051811385124085646)),
 (1037, np.float64(0.05173903965925509)),
 (222, np.float64(0.05167232262356085)),
 (206, np.float64(0.051589288145000176)),
 (256, np.float64(0.051429008052207514)),
 (839, np.float64(0.05114771692875645)),
 (41, np.float64(0.0510549739387144)),
 (875, np.float64(0.0510549739387144)),
 (892, np.float64(0.0510549739387144)),
 (411, np.float64(0.05068898374371097)),
 (975, np.float64(0.05057621612072544)),
 (778, np.float64(0.050389931082158314)),
 (37, np.float64(0.05038993108215831)),
 (67, np.float64(0.05038993108215831)),
 (83, np.float64(0.05038993108215831)),
 (501, np.float64(0.05033075322136328)),
 (223, np.float64(0.04990306042674866)),
 (741, np.float64(0.04990306042674866)),
 (1151, np.float64(0.04990306042674866)),

In [533]:
# The below is code for top 20 Highest recommended movies
count = 0
for i in sorted_similar_score:
    if i[0] == index_of_the_movie:
        continue   # skip same movie
    
    print(df_new.iloc[i[0]]['title'])
    count += 1
    
    if count >= 10:
        break

Captain America: The First Avenger
Captain America: Civil War
Iron Man 3
Avengers: Age of Ultron
The Avengers
Ant-Man
Thor: The Dark World
Deadpool
Iron Man 2
Fantastic Four