In [1]:
# starting with content based filtering

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
# loading the data from a CSV file to pandas data
df1 = pd.read_csv("../dataset/tmdb_5000_credits.csv")
df1.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [3]:
# loading the data from a CSV file to pandas data
df2 = pd.read_csv("../dataset/tmdb_5000_movies.csv")
df2.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [84]:
df = df1.merge(df2 , on="title" , how='inner')
df.head(2)

,movie_id,title,cast,crew,budget,genres,homepage,id,keywords,original_language,...,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,vote_average,vote_count
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,...,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,7.2,11800
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,...,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",6.9,4500

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   movie_id              4809 non-null   int64
 1   title                 4809 non-null   object
 2   cast                  4809 non-null   object
 3   crew                  4809 non-null   object
 4   budget                4809 non-null   int64
 5   genres                4809 non-null   object
 6   homepage              1713 non-null   object
 7   id                    4809 non-null   int64
 8   keywords              4809 non-null   object
 9   original_language     4809 non-null   object
 10  original_title        4809 non-null   object
 11  overview              4806 non-null   object
 12  popularity            4809 non-null   float64
 13  production_companies  4809 non-null   object
 14  production_countries  4809 non-null   object
 15  release_date          4808 non-null   object
 16  revenue               4809 non-null   int64
 17  runtime               4807 non-null   float64
 18  spoken_languages      4809 non-null   object
 19  status                4809 non-null   object
 20  tagline               3965 non-null   object
 21  vote_average          4809 non-null   float64
 22  vote_count            4809 non-null   int64
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [86]:
selected_features = ['movie_id' , 'title','overview' , 'genres','keywords','cast','crew']
print(selected_features)
df[selected_features].isnull().sum()

['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [87]:
# Checking for Null values and filling it with empty string.
# for feature in selected_features:
#     df[feature] = df[feature].fillna('')
df.dropna(inplace=True)
df[selected_features].isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [88]:
df.iloc[0][selected_features]

movie_id                                                19995
title                                                  Avatar
overview    In the 22nd century, a paraplegic Marine is di...
genres      [{"id": 28, "name": "Action"}, {"id": 12, "nam...
keywords    [{"id": 1463, "name": "culture clash"}, {"id":...
cast        [{"cast_id": 242, "character": "Jake Sully", "...
crew        [{"credit_id": "52fe48009251416c750aca23", "de...
Name: 0, dtype: object

In [89]:
import json
def preprocess(x):
    L = []
    for i in x:
        L.append(i["name"])
    return L

def preprocess_cast(x):
    L = []
    for i in x[:3]:
        L.append(i["name"])
    return L
# preprocess(json.loads(df.iloc[0]['genres']))
df['genres'] = df['genres'].apply(json.loads).apply(preprocess)
df['keywords'] = df['keywords'].apply(json.loads).apply(preprocess)
df['cast'] = df['cast'].apply(json.loads).apply(preprocess_cast)
df['crew'] = df['crew'].apply(json.loads).apply(lambda x: [i['name'] for i in x if i['job'] == 'Director'])

In [90]:
df[selected_features].iloc[0]

movie_id                                                19995
title                                                  Avatar
overview    In the 22nd century, a paraplegic Marine is di...
genres          [Action, Adventure, Fantasy, Science Fiction]
keywords    [culture clash, future, space war, space colon...
cast         [Sam Worthington, Zoe Saldana, Sigourney Weaver]
crew                                          [James Cameron]
Name: 0, dtype: object

In [92]:
df['genres'] = df['genres'].apply(lambda x: [i.replace(" ","") for i in x])
df['keywords'] = df['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
df['cast'] = df['cast'].apply(lambda x: [i.replace(" ","") for i in x])
df['crew'] = df['crew'].apply(lambda x: [i.replace(" ","")  for i in x])

In [93]:
df[selected_features].iloc[0]

movie_id                                                19995
title                                                  Avatar
overview    In the 22nd century, a paraplegic Marine is di...
genres           [Action, Adventure, Fantasy, ScienceFiction]
keywords    [cultureclash, future, spacewar, spacecolony, ...
cast            [SamWorthington, ZoeSaldana, SigourneyWeaver]
crew                                           [JamesCameron]
Name: 0, dtype: object

In [94]:
# Combining all the 5 selected features
combined_string = df['overview'] + " " + df['genres'].apply(lambda x: " ".join(x)) + " " + df['keywords'].apply(lambda x: " ".join(x)) + " " + df['cast'].apply(lambda x: " ".join(x)) + " " + df['crew'].apply(lambda x: " ".join(x))
df['tags'] = combined_string.apply(lambda x: x.lower())

In [95]:
df_new = df[['movie_id','title','tags']]
df_new.head(1)

   movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a paraplegic marine is di...

In [96]:
# Converting all the Text Data to Numbering vectors
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(df['tags'])

In [97]:
# Cosine similarity of all the feature vectors
# The Thing it does is that bruteforce From Row1 to all the Rows in the DataFrame.
similarity = cosine_similarity(feature_vectors)

In [98]:
df_new["title"].iloc[1]

"Pirates of the Caribbean: At World's End"

In [99]:
df_new["title"].iloc[1]

"Pirates of the Caribbean: At World's End"

In [100]:
movie_names = df_new['title'].tolist()
movie_names

['Avatar',
 "Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises',
 'John Carter',
 'Spider-Man 3',
 'Tangled',
 'Avengers: Age of Ultron',
 'Harry Potter and the Half-Blood Prince',
 'Batman v Superman: Dawn of Justice',
 'Quantum of Solace',
 "Pirates of the Caribbean: Dead Man's Chest",
 'The Lone Ranger',
 'Man of Steel',
 'The Avengers',
 'Pirates of the Caribbean: On Stranger Tides',
 'Men in Black 3',
 'The Hobbit: The Battle of the Five Armies',
 'The Amazing Spider-Man',
 'Robin Hood',
 'The Hobbit: The Desolation of Smaug',
 'The Golden Compass',
 'Titanic',
 'Captain America: Civil War',
 'Jurassic World',
 'Skyfall',
 'Spider-Man 2',
 'Iron Man 3',
 'Alice in Wonderland',
 'Transformers: Revenge of the Fallen',
 'Transformers: Age of Extinction',
 'Oz: The Great and Powerful',
 'The Amazing Spider-Man 2',
 'TRON: Legacy',
 'Cars 2',
 'Green Lantern',
 'Toy Story 3',
 'Terminator Salvation',
 'Furious 7',
 'World War Z',
 'X-Men: Days of Future Past',
 'Jack the Giant Slayer',
 'Prince of Persia: The Sands of Time',
 'Pacific Rim',
 'Transformers: Dark of the Moon',
 'Indiana Jones and the Kingdom of the Crystal Skull',
 'The Good Dinosaur',
 'Brave',
 'WALL·E',
 '2012',
 'A Christmas Carol',
 'Jupiter Ascending',
 'The Legend of Tarzan',
 'X-Men: Apocalypse',
 'The Dark Knight',
 'Monsters vs Aliens',
 'Iron Man',
 'Hugo',
 'The Mummy: Tomb of the Dragon Emperor',
 'Suicide Squad',
 'Evan Almighty',
 'Edge of Tomorrow',
 'G.I. Joe: The Rise of Cobra',
 'Inside Out',
 'Iron Man 2',
 'Snow White and the Huntsman',
 'Maleficent',
 'Dawn of the Planet of the Apes',
 'Captain America: The Winter Soldier',
 'Shrek Forever After',
 'Tomorrowland',
 'Big Hero 6',
 'Wreck-It Ralph',
 'Independence Day: Resurgence',
 'How to Train Your Dragon',
 'Guardians of the Galaxy',
 'Interstellar',
 'Inception',
 'The Hobbit: An Unexpected Journey',
 'The Curious Case of Benjamin Button',
 'X-Men: First Class',
 'The Hunger Games: Mockingjay - Part 2',
 "The Sorcerer's Apprentice",
 'Poseidon',
 'Alice Through the Looking Glass',
 'Shrek the Third',
 'Warcraft',
 'Terminator Genisys',
 'Transformers',
 'Harry Potter and the Order of the Phoenix',
 'Harry Potter and the Goblet of Fire',
 'Hancock',
 'I Am Legend',
 'Charlie and the Chocolate Factory',
 'Ratatouille',
 'Batman Begins',
 'Madagascar: Escape 2 Africa',
 'Night at the Museum: Battle of the Smithsonian',
 'X-Men Origins: Wolverine',
 'Frozen',
 'Thor: The Dark World',
 'Mad Max: Fury Road',
 'Thor',
 'Bolt',
 'G-Force',
 'Wrath of the Titans',
 'Dark Shadows',
 'Mission: Impossible - Rogue Nation',
 'The Wolfman',
 'Bee Movie',
 'Kung Fu Panda 2',
 'The Last Airbender',
 'Mission: Impossible III',
 'Mars Needs Moms',
 'Flushed Away',
 'Die Another Day',
 'Ghostbusters',
 'Men in Black II',
 'Beowulf',
 'Kung Fu Panda 3',
 'Mission: Impossible - Ghost Protocol',
 'Rise of the Guardians',
 'Fun with Dick and Jane',
 'Exodus: Gods and Kings',
 'Spider-Man',
 'How to Train Your Dragon 2',
 'Watchmen',
 'Captain America: The First Avenger',
 'The World Is Not Enough',
 'Master and Commander: The Far Side of the World',
 'Happy Feet Two',
 'The BFG',
 'The Revenant',
 'Turbo',
 'Rango',
 'The Bourne Ultimatum',
 'Kung Fu Panda',
 'Ant-Man',
 'The Hunger Games: Catching Fire',
 'Home',
 'Salt',
 'Noah',
 'The Adventures of Tintin',
 'Megamind',
 "Harry Potter and the Philosopher's Stone",
 'R.I.P.D.',
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'The Hunger Games: Mockingjay - Part 1',
 'The Da Vinci Code',
 'Rio 2',
 'Fast Five',
 'Sherlock Holmes: A Game of Shadows',
 'Clash of the Titans',
 'The Bourne Legacy',
 'How the Grinch Stole Christmas',
 'The Day After Tomorrow',
 'Mission: Impossible II',
 'Life of Pi',
 'Ghost Rider',
 'Jason Bourne',
 'Prometheus',
 'RoboCop',
 'Speed Racer',
 'How Do You Know',
 'Knight and Day',
 'Oblivion',
 'Star Wars: Episode III - Revenge of the Sith',
 'Star Wars: Episode II - Attack of the Clones',
 'Monsters, Inc.',
 'The Wolverine',
 'Star Wars: Episode I - The Phantom Menace',
 'The Croods',
 "The Huntsman: Winter's War",
 'Teenage Mutant Ninja Turtles',
 'Gravity',
 'Teenage Mutant Ninja Turtles: Out of the Shadows',
 'Fantastic Four',
 'San Andreas',
 'Tomorrow Never Dies',
 "Ocean's Twelve",
 'Insurgent',
 'The Green Hornet',
 '300: Rise of an Empire',
 'The Smurfs',
 'Home on the Range',
 'Allegiant',
 'Real Steel',
 'The Smurfs 2',
 "Ender's Game",
 'The Lord of the Rings: The Fellowship of the Ring',
 'Kingdom of Heaven',
 'The Princess and the Frog',
 'The Martian',
 'The Island',
 'Casino Royale',
 'Public Enemies',
 'American Gangster',
 'The Taking of Pelham 1 2 3',
 'Little Fockers',
 'The Other Guys',
 'Eraser',
 'Django Unchained',
 'The Expendables 2',
 'Eragon',
 'Where the Wild Things Are',
 'The Tourist',
 'End of Days',
 'The Wolf of Wall Street',
 'Cloud Atlas',
 "Legend of the Guardians: The Owls of Ga'Hoole",
 'The Expendables 3',
 'Point Break',
 'In the Heart of the Sea',
 'Green Zone',
 'The Peanuts Movie',
 'Gangs of New York',
 "Surf's Up",
 'Sex and the City 2',
 'Ice Age: Continental Drift',
 'Cinderella',
 'The Lovely Bones',
 'Finding Nemo',
 'The Lord of the Rings: The Return of the King',
 'The Lord of the Rings: The Two Towers',
 'Seventh Son',
 'Rise of the Planet of the Apes',
 'A Good Day to Die Hard',
 'The Incredibles',
 'Men in Black',
 'Toy Story 2',
 'Cloudy with a Chance of Meatballs',
 'Ice Age: Dawn of the Dinosaurs',
 'The Departed',
 'Tropic Thunder',
 'The Girl with the Dragon Tattoo',
 'Sherlock Holmes',
 'Ben-Hur',
 'Atlantis: The Lost Empire',
 'Alvin and the Chipmunks: The Road Chip',
 "You Don't Mess with the Zohan",
 'Pixels',
 'Contact',
 'The Interpreter',
 'Percy Jackson: Sea of Monsters',
 'Now You See Me 2',
 'Rio',
 'Cinderella Man',
 'Seabiscuit',
 'Happy Feet',
 'The Bourne Supremacy',
 "Ocean's Eleven",
 'The Three Musketeers',
 'Hotel Transylvania',
 'Enchanted',
 'Safe House',
 'Tower Heist',
 'The Holiday',
 "It's Complicated",
 "Ocean's Thirteen",
 'Open Season',
 'Divergent',
 'The Rundown',
 'Memoirs of a Geisha',
 'The Fast and the Furious: Tokyo Drift',
 'Arthur Christmas',
 'Meet Joe Black',
 'Collateral Damage',
 'Scott Pilgrim vs. the World',
 'Dredd',
 'Cats & Dogs 2 : The Revenge of Kitty Galore',
 'Jumper',
 'Bruce Almighty',
 'The Expendables',
 'Mission: Impossible',
 'The Hunger Games',
 'The Hangover Part II',
 'RED 2',
 'Alvin and the Chipmunks: Chipwrecked',
 'Grown Ups 2',
 'Get Smart',
 'Shutter Island',
 'Just Go with It',
 'Space Jam',
 'Yogi Bear',
 'Zookeeper',
 'The Time Machine',
 'The Legend of Zorro',
 'Mars Attacks!',
 'Surrogates',
 'Walking With Dinosaurs',
 'Nine',
 'The Last Witch Hunter',
 'Oceans',
 'A Sound of Thunder',
 'A Beautiful Mind',
 'The Lion King',
 'Journey 2: The Mysterious Island',
 'Jack and Jill',
 'The Little Prince',
 'The Secret Life of Pets',
 'Despicable Me 2',
 'Children of Men',
 'Wanted',
 'Ice Age: The Meltdown',
 'Hairspray',
 'Grown Ups',
 'The Terminal',
 'Vertical Limit',
 "Charlie Wilson's War",
 'Dreamgirls',
 'Killers',
 'Monster House',
 'Immortals',
 'Soldier',
 'Minions',
 'Sucker Punch',
 'Sphere',
 'The Angry Birds Movie',
 "Fool's Gold",
 'Funny People',
 'The Kingdom',
 'Talladega Nights: The Ballad of Ricky Bobby',
 'The Simpsons Movie',
 'Shrek 2',
 'Cars',
 'xXx',
 'The SpongeBob Movie: Sponge Out of Water',
 'Inglourious Basterds',
 'S.W.A.T.',
 'AVP: Alien vs. Predator',
 'Alvin and the Chipmunks: The Squeakquel',
 'Battle: Los Angeles',
 'War Horse',
 'The Monuments Men',
 'Wall Street: Money Never Sleeps',
 'Stardust',
 'The Dilemma',
 'Underworld: Awakening',
 'Rock of Ages',
 'Osmosis Jones',
 "Legends of Oz: Dorothy's Return",
 'Blackhat',
 'Sky Captain and the World of Tomorrow',
 'Escape Plan',
 'The Sum of All Fears',
 'The Twilight Saga: Eclipse',
 'Despicable Me',
 'Agora',
 'Hall Pass',
 'The Finest Hours',
 'Body of Lies',
 'Dinner for Schmucks',
 'Entrapment',
 'Ice Age',
 'Dreamcatcher',
 'The Matrix',
 'Les Misérables',
 "You've Got Mail",
 'Due Date',
 'Unbroken',
 'Space Cowboys',
 'The Kid',
 'The Dictator',
 'Eyes Wide Shut',
 'Focus',
 'This Means War',
 'Blade: Trinity',
 'Resident Evil: Retribution',
 'Death Race',
 'Fight Club',
 'I, Frankenstein',
 'Elektra',
 'Sin City: A Dame to Kill For',
 'Everest',
 'Perfume: The Story of a Murderer',
 'Austin Powers in Goldmember',
 'Astro Boy',
 'Jurassic Park',
 'Little Man',
 'U-571',
 'The Love Guru',
 'The Hateful Eight',
 'Hop',
 '300',
 'Meet the Fockers',
 'Marley & Me',
 'The Green Mile',
 'Wild Hogs',
 'Chicken Little',
 'Gone Girl',
 'The Bourne Identity',
 'GoldenEye',
 '2 Guns',
 'Cats & Dogs',
 'The Italian Job',
 'Couples Retreat',
 'Maze Runner: The Scorch Trials',
 'Eat Pray Love',
 'The Scorpion King',
 'Jack Reacher',
 'This Is It',
 'Contagion',
 'Coraline',
 'The Happening',
 'The Shaggy Dog',
 'Hellboy',
 'ParaNorman',
 'The Tale of Despereaux',
 'London Has Fallen',
 'Shooter',
 'The Lego Movie',
 'Gangster Squad',
 'Invictus',
 'State of Play',
 'Duplicity',
 'Planet 51',
 'Trouble with the Curve',
 'Righteous Kill',
 'The Soloist',
 'xXx: State of the Union',
 'Priest',
 "Winter's Tale",
 'The Mortal Instruments: City of Bones',
 'Meet Dave',
 'Inkheart',
 'The Spirit',
 'Mortdecai',
 'In the Name of the King: A Dungeon Siege Tale',
 'Deadpool',
 'American Sniper',
 'Goosebumps',
 'The Flintstones in Viva Rock Vegas',
 'Leatherheads',
 'The Internship',
 'Resident Evil: Afterlife',
 'Red Tails',
 "That's My Boy",
 'After the Sunset',
 'Ghost Rider: Spirit of Vengeance',
 'The Pacifier',
 'Alvin and the Chipmunks',
 'Captain Phillips',
 'Date Night',
 'Kill Bill: Vol. 1',
 'The Forbidden Kingdom',
 'Evita',
 'Paddington',
 'Semi-Pro',
 'Changeling',
 'Imagine That',
 'Burlesque',
 'Blade II',
 'Seven Pounds',
 'The Godfather: Part III',
 'You, Me and Dupree',
 'Gigli',
 "All the King's Men",
 'Lucky You',
 'Catch Me If You Can',
 'Zero Dark Thirty',
 'The Break-Up',
 "Valentine's Day",
 'The Dukes of Hazzard',
 'The Change-Up',
 'Man on the Moon',
 'From Paris with Love',
 'The Twilight Saga: New Moon',
 'Shrek',
 'The Adjustment Bureau',
 'Ted',
 'Super 8',
 'Erin Brockovich',
 '22 Jump Street',
 'Central Intelligence',
 "Daddy's Home",
 'Into the Woods',
 'Inside Man',
 'We Bought a Zoo',
 'Knowing',
 'Crazy, Stupid, Love.',
 'Moneyball',
 'V for Vendetta',
 'Hansel & Gretel: Witch Hunters',
 'I Am Number Four',
 'Syriana',
 '13 Hours: The Secret Soldiers of Benghazi',
 'Silent Hill',
 'American Reunion',
 'The Judge',
 'The Adventures of Sharkboy and Lavagirl',
 'Ninja Assassin',
 'Marmaduke',
 'Hereafter',
 'Hannibal Rising',
 'The Host',
 'The International',
 'Escape from L.A.',
 'The Iron Giant',
 'Free State of Jones',
 'Eastern Promises',
 'Your Highness',
 'Fair Game',
 'Gamer',
 'Zoolander 2',
 'Drive Angry',
 'The Boat That Rocked',
 'Indiana Jones and the Last Crusade',
 'Chappie',
 'K-PAX',
 '3:10 to Yuma',
 'Taken 3',
 "Happily N'Ever After",
 'Star Trek: First Contact',
 'Jonah Hex',
 'The Infiltrator',
 'The Bucket List',
 'Prisoners',
 'The Muppets',
 'Blade',
 'Love Actually',
 "A Bug's Life",
 'Resident Evil: Extinction',
 'Savages',
 'Cellular',
 'The Ant Bully',
 'Across the Universe',
 'Babylon A.D.',
 'Aliens in the Attic',
 'All the Pretty Horses',
 'Curse of the Golden Flower',
 'Bangkok Dangerous',
 'Love in the Time of Cholera',
 'Johnny English Reborn',
 'Foodfight!',
 'Argo',
 'The Bounty Hunter',
 'Underworld: Evolution',
 'Victor Frankenstein',
 'Unleashed',
 'The Sweetest Thing',
 'The Mechanic',
 '21 Jump Street',
 'Notting Hill',
 'Along Came Polly',
 'Licence to Kill',
 'Red Riding Hood',
 'One for the Money',
 "The Warrior's Way",
 '8 Mile',
 'Why I Did (Not) Eat My Father',
 'Man on a Ledge',
 'American Hustle',
 'The Proposal',
 'Back to the Future Part II',
 'Lucy',
 'Fifty Shades of Grey',
 'Lone Survivor',
 'The Conjuring 2',
 'The Social Network',
 "He's Just Not That Into You",
 'Back to the Future Part III',
 'Julie & Julia',
 'The Talented Mr. Ripley',
 'The Intern',
 'Ride Along 2',
 'Sin City',
 'Vantage Point',
 'I Love You, Man',
 '17 Again',
 'The Final Destination',
 'Get Him to the Greek',
 'Shall We Dance?',
 'The Lincoln Lawyer',
 'Unknown',
 'The Prestige',
 'Escape from Planet Earth',
 'The Living Daylights',
 'The Lake House',
 'The Odd Life of Timothy Green',
 'Gothika',
 'Aliens vs Predator: Requiem',
 'Paul',
 'Scream 4',
 'Final Destination 5',
 'Drillbit Taylor',
 'Extremely Loud & Incredibly Close',
 'Morning Glory',
 'Rent',
 'The Reaping',
 'Colombiana',
 'Marie Antoinette',
 'Fantastic Mr. Fox',
 'Memoirs of an Invisible Man',
 'Amélie',
 'Big Miracle',
 'Pandorum',
 'A Thousand Words',
 'Disturbia',
 'The Hunting Party',
 'Snowpiercer',
 'Because I Said So',
 'Frankenweenie',
 'Red Cliff',
 'The Ugly Truth',
 'Water for Elephants',
 'Enough',
 'Angel Eyes',
 'Precious',
 'The Thing',
 'Riddick',
 'City of Ember',
 'The 5th Wave',
 'Creed',
 'The Town',
 "What to Expect When You're Expecting",
 'Magnolia',
 'Cop Out',
 'How to Be Single',
 'Dolphin Tale',
 'Twilight',
 "We're the Millers",
 'Never Say Never Again',
 'Hot Tub Time Machine',
 'Dolphin Tale 2',
 'A Man Apart',
 'The Rite',
 'Space Chimps',
 'The Hangover',
 'The Blind Side',
 'Horrible Bosses',
 'True Grit',
 'The Devil Wears Prada',
 'Identity Thief',
 '21',
 'Sky High',
 'Secretariat',
 'Friends with Benefits',
 'Neighbors 2: Sorority Rising',
 'This Is 40',
 'Old Dogs',
 'License to Wed',
 'Resident Evil',
 'Max Payne',
 'In Time',
 'The Back-Up Plan',
 'Something Borrowed',
 'The Pianist',
 'J. Edgar',
 'Untraceable',
 'Nanny McPhee and the Big Bang',
 'Ella Enchanted',
 'Concussion',
 'Abduction',
 'Broken City',
 'Premium Rush',
 'Furry Vengeance',
 'Walk Hard: The Dewey Cox Story',
 'The Young Victoria',
 'Whiteout',
 'The Tree of Life',
 'Punisher: War Zone',
 'The Walk',
 'The Maze Runner',
 'The Fountain',
 'Exit Wounds',
 'Thunder and the House of Magic',
 'The Darkest Hour',
 'The Punisher',
 'Safe',
 'Return of the Jedi',
 'Wanderlust',
 'Nacho Libre',
 'Bridesmaids',
 'This Is the End',
 'Takers',
 'Big Mommas: Like Father, Like Son',
 'Source Code',
 'The Number 23',
 'Repo Men',
 'The Good German',
 'Apocalypse Now',
 'Going the Distance',
 'Moonraker',
 'Extraordinary Measures',
 'Remember the Titans',
 'The Hunt for Red October',
 'Se7en',
 'District 9',
 'Million Dollar Baby',
 'The Notebook',
 '27 Dresses',
 'Hannah Montana: The Movie',
 'Up in the Air',
 'Looper',
 'Forgetting Sarah Marshall',
 'Four Brothers',
 'Baby Mama',
 'Bride Wars',
 'A View to a Kill',
 'The Curse of the Were-Rabbit',
 'Letters to Juliet',
 'The Three Stooges',
 'Corpse Bride',
 'Drag Me to Hell',
 'The Age of Adaline',
 'Step Up 3D',
 'Stranger Than Fiction',
 '30 Days of Night',
 'The Cabin in the Woods',
 'Meet the Spartans',
 'Hanna',
 'Larry Crowne',
 'Carrie',
 'Side Effects',
 'Winnie the Pooh',
 'Sanctum',
 'The Five-Year Engagement',
 'The Next Three Days',
 'Ultraviolet',
 'Love & Other Drugs',
 'North Country',
 'Splice',
 'Pride and Glory',
 'Alex & Emma',
 'Fright Night',
 'The Last Stand',
 'Hoodwinked Too! Hood VS. Evil',
 'An Unfinished Life',
 "Barney's Version",
 'Runner Runner',
 'Antitrust',
 'The Promise',
 'The Assassination of Jesse James by the Coward Robert Ford',
 '1911',
 'Machine Gun Preacher',
 'Savva. Heart of the Warrior',
 'Sausage Party',
 'The Boss',
 'Aladdin',
 'Straight Outta Compton',
 'Indiana Jones and the Temple of Doom',
 'Florence Foster Jenkins',
 'The Big Short',
 'Taking Woodstock',
 'Dawn of the Dead',
 'For Your Eyes Only',
 'No Reservations',
 '30 Minutes or Less',
 'Alexander and the Terrible, Horrible, No Good, Very Bad Day',
 'Pride & Prejudice',
 'Blade Runner',
 'Ghosts of Mars',
 'Our Brand Is Crisis',
 'Pride and Prejudice and Zombies',
 'Octopussy',
 'Knocked Up',
 "My Sister's Keeper",
 'Notes on a Scandal',
 'Rendition',
 'Joyful Noise',
 'About a Boy',
 'Anonymous',
 'The Duchess',
 'Return to Oz',
 'Case 39',
 'Mindhunters',
 'What Just Happened',
 'Paul Blart: Mall Cop',
 'The 40 Year Old Virgin',
 'Pineapple Express',
 'Legion',
 'Pain & Gain',
 'Agent Cody Banks 2: Destination London',
 'Self/less',
 'The Passion of the Christ',
 'Gran Torino',
 'W.',
 "Schindler's List",
 'The Help',
 'Cloverfield',
 'No Strings Attached',
 'Bridge to Terabithia',
 'A Madea Christmas',
 'The Grey',
 'GoodFellas',
 'Contraband',
 'The House Bunny',
 'Million Dollar Arm',
 'The Giver',
 'Good Luck Chuck',
 'August Rush',
 'The Gambler',
 'Eddie the Eagle',
 'The Losers',
 "Don't Be Afraid of the Dark",
 'The Box',
 'Legend',
 'Shark Night',
 'The Conspirator',
 'Big Trouble in Little China',
 'Warrior',
 'Stop-Loss',
 'The Possession',
 'Straw Dogs',
 'The Road',
 'BloodRayne',
 'Carnage',
 'The Best Offer',
 'Little White Lies',
 'On the Road',
 'Rocky Balboa',
 'Old School',
 'Zack and Miri Make a Porno',
 'The Men Who Stare at Goats',
 'Ready to Rumble',
 "I Don't Know How She Does It",
 'Piranha 3D',
 'Faster',
 'Zombieland',
 'The Empire Strikes Back',
 'The Ides of March',
 'Pitch Black',
 'Her',
 'Anywhere But Here',
 'Haywire',
 'Harley Davidson and the Marlboro Man',
 'In the Valley of Elah',
 'Coco Before Chanel',
 'Bodyguards and Assassins',
 '1408',
 'Spaceballs',
 'The Water Diviner',
 "There's Something About Mary",
 'The Game Plan',
 'Underworld',
 'Derailed',
 'The Informant!',
 'Hail, Caesar!',
 'The Transporter Refueled',
 'Hit & Run',
 'Stone',
 'Michael Clayton',
 'Death at a Funeral',
 'Silver Linings Playbook',
 'Freedom Writers',
 'For Colored Girls',
 'Never Back Down',
 'Tinker Tailor Soldier Spy',
 'The Beaver',
 'Raiders of the Lost Ark',
 'Pulse',
 'The Conjuring',
 'School of Rock',
 'The Descendants',
 'Why Did I Get Married Too?',
 'Me Before You',
 "Madea's Witness Protection",
 'Bad Moms',
 'Boogeyman',
 'Spotlight',
 'The Grudge 2',
 'Vampires Suck',
 'Team America: World Police',
 'Milk',
 'A Very Harold & Kumar Christmas',
 'The Stepfather',
 'The Debt',
 'One Missed Call',
 'Eternal Sunshine of the Spotless Mind',
 'Daybreakers',
 "She's Out of My League",
 'Alpha and Omega',
 'Nerve',
 'Vampires',
 "My Best Friend's Girl",
 'Reign Over Me',
 'Into the Wild',
 'From Dusk Till Dawn',
 'The Country Bears',
 'The Kite Runner',
 '21 Grams',
 'Capitalism: A Love Story',
 'Secret in Their Eyes',
 'Disaster Movie',
 "What's Your Number?",
 'Lockout',
 'Crank: High Voltage',
 'One Night with the King',
 '12 Rounds',
 'Let Me In',
 'Triple 9',
 'Burnt',
 "Everybody's Fine",
 'Superbabies: Baby Geniuses 2',
 'Inherent Vice',
 'Doogal',
 'An American Carol',
 'Little Boy',
 'A Dangerous Method',
 'A Scanner Darkly',
 'Bandslam',
 'A Most Violent Year',
 'Flash of Genius',
 "I'm Not There.",
 'The Brothers Bloom',
 'My All American',
 'The Children of Huang Shi',
 'The Yards',
 'Dylan Dog: Dead of Night',
 'Zambezia',
 'Survivor',
 'Bad Teacher',
 'A Cinderella Story',
 'Back to the Future',
 'Fight Valley',
 'The Switch',
 'Spirited Away',
 'The Book Thief',
 'Sex Drive',
 'Leap Year',
 'Take Me Home Tonight',
 'Adaptation.',
 'The Invention of Lying',
 'Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan',
 'Left Behind',
 'Bad Santa',
 'Diary of a Wimpy Kid: Rodrick Rules',
 'Prom Night',
 'Mean Girls',
 'The Fog',
 'Soul Surfer',
 'Love Happens',
 'Love the Coopers',
 'Steve Jobs',
 'I Love You, Beth Cooper',
 'Youth in Revolt',
 'Getaway',
 'The Last Station',
 'RockNRolla',
 "Mao's Last Dancer",
 'Midnight Special',
 'The Informers',
 'Superbad',
 'Hoodwinked!',
 'Hotel Rwanda',
 'Hitman',
 'Black Nativity',
 'Sideways',
 'Halloween',
 'Good Boy!',
 "Smokin' Aces",
 'Saw: The Final Chapter',
 'Beastly',
 'The Hills Have Eyes',
 'Pitch Perfect',
 'Evil Dead',
 'My Life in Ruins',
 'Running Scared',
 'Roar',
 'Southland Tales',
 'The Apparition',
 'Fur: An Imaginary Portrait of Diane Arbus',
 'Becoming Jane',
 'The Artist',

In [114]:
# rapidfuzz we are using to find the closest Match.
# Let us say if there are any spelling mistakes in the input array
# we need the correct spelling to find the index and check the cosine similarity
from rapidfuzz import process

movies = df_new['title'].tolist()

user_input = "pirate"

find_close_match = process.extract(user_input, movies , limit=5)

print(find_close_match)

[("Pirates of the Caribbean: At World's End", 75.00000000000001, 1), ("Pirates of the Caribbean: Dead Man's Chest", 75.00000000000001, 11), ('Pirates of the Caribbean: On Stranger Tides', 75.00000000000001, 15), ('The Conspirator', 75.00000000000001, 798), ('Spirited Away', 75.00000000000001, 916)]

In [113]:
df_new.head(1)

   movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a paraplegic marine is di...

In [122]:
# Our Agenda is to first find the index of the Movie with title.
index_of_the_movie = df_new[df_new.title == list(find_close_match[0])[0]].iloc[0].movie_id
index_of_the_movie

np.int64(285)

In [126]:
# In the similarity_score array we have bruteforce array with all combinations
# of solutions we get list of all movies from the index.
similarity_score = list(enumerate(similarity[index_of_the_movie]))

In [127]:
# So in the below code we are basically sorting in descending order
# to find the Highest Recommended movies
sorted_similar_score = sorted(similarity_score , key= lambda x : x[1] , reverse=True)
sorted_similar_score

[(285, np.float64(1.0000000000000004)),
 (208, np.float64(0.1948923866575835)),
 (87, np.float64(0.13082068982512904)),
 (301, np.float64(0.11560606559076797)),
 (733, np.float64(0.11086255981865376)),
 (16, np.float64(0.1105950589028568)),
 (693, np.float64(0.11047976719546614)),
 (885, np.float64(0.10782882073754609)),
 (160, np.float64(0.104718541667668)),
 (40, np.float64(0.09826014315034357)),
 (1323, np.float64(0.09503131927774697)),
 (643, np.float64(0.0913774547799248)),
 (1017, np.float64(0.08801550660411041)),
 (678, np.float64(0.08549874128720383)),
 (431, np.float64(0.08397177397894162)),
 (366, np.float64(0.08313668459105518)),
 (468, np.float64(0.08307911166028191)),
 (1104, np.float64(0.08190849613022742)),
 (58, np.float64(0.08167719893175104)),
 (101, np.float64(0.0796191030203015)),
 (188, np.float64(0.07765323850165598)),
 (560, np.float64(0.07634802076031483)),
 (125, np.float64(0.07509377630156179)),
 (402, np.float64(0.07470191245204569)),
 (370, np.float64(0.07413033724694498)),
 (1359, np.float64(0.07381676249249784)),
 (622, np.float64(0.07330593921754827)),
 (1100, np.float64(0.07273908367866908)),
 (521, np.float64(0.07256534266078882)),
 (68, np.float64(0.07231032255764455)),
 (0, np.float64(0.07196935156265105)),
 (1188, np.float64(0.07168713995384188)),
 (599, np.float64(0.07144621168236642)),
 (899, np.float64(0.07023678099583773)),
 (237, np.float64(0.06922169543529849)),
 (1312, np.float64(0.06727117859667568)),
 (1210, np.float64(0.06703633173234656)),
 (70, np.float64(0.06568370220196502)),
 (548, np.float64(0.06548737957110674)),
 (1067, np.float64(0.06541854568330788)),
 (37, np.float64(0.06507656060845075)),
 (15, np.float64(0.06479010933528667)),
 (1177, np.float64(0.06410100808685709)),
 (13, np.float64(0.06389219844818186)),
 (260, np.float64(0.063409769510992)),
 (1465, np.float64(0.06336906916595539)),
 (817, np.float64(0.06237132440713074)),
 (909, np.float64(0.062128536599522347)),
 (113, np.float64(0.061889097383216116)),
 (75, np.float64(0.06144160532121176)),
 (1335, np.float64(0.061180446623481356)),
 (166, np.float64(0.06108659890171841)),
 (23, np.float64(0.0610353070910819)),
 (1308, np.float64(0.05983746800055706)),
 (816, np.float64(0.05924041826018503)),
 (1028, np.float64(0.05905271176403021)),
 (1247, np.float64(0.05899728637867013)),
 (350, np.float64(0.05880051718525402)),
 (367, np.float64(0.05866445936624071)),
 (64, np.float64(0.05862640613847206)),
 (286, np.float64(0.05854046823876325)),
 (869, np.float64(0.05841848974950951)),
 (43, np.float64(0.058214305816576446)),
 (1126, np.float64(0.05783799420964298)),
 (1129, np.float64(0.057815404521933504)),
 (702, np.float64(0.05771554550696174)),
 (483, np.float64(0.057264125340839)),
 (581, np.float64(0.05720402418298455)),
 (356, np.float64(0.05713486149257173)),
 (185, np.float64(0.05702799552724082)),
 (17, np.float64(0.05660364440293527)),
 (913, np.float64(0.056314374175693016)),
 (872, np.float64(0.05629237581336308)),
 (1425, np.float64(0.05626586068705925)),
 (186, np.float64(0.05540709780444536)),
 (33, np.float64(0.055232002130101474)),
 (1098, np.float64(0.05522177185062684)),
 (800, np.float64(0.055097273428524274)),
 (41, np.float64(0.054948938429873216)),
 (526, np.float64(0.054852683325413425)),
 (505, np.float64(0.05479758550243644)),
 (633, np.float64(0.05421702613458497)),
 (288, np.float64(0.05419437936271423)),
 (1320, np.float64(0.054157329481543864)),
 (24, np.float64(0.05380414378189101)),
 (1469, np.float64(0.05372903037604073)),
 (866, np.float64(0.05343825721094958)),
 (26, np.float64(0.05324962341629008)),
 (659, np.float64(0.05305952448067526)),
 (946, np.float64(0.0526516017189238)),
 (753, np.float64(0.0526399618132576)),
 (512, np.float64(0.05219469687345515)),
 (62, np.float64(0.05208210508709994)),
 (355, np.float64(0.05172868212656815)),
 (1049, np.float64(0.05166759569860253)),
 (1271, np.float64(0.05155795773302961)),
 (74, np.float64(0.05154416002315358)),
 (1376, np.float64(0.051498794986323405)),
 (373, np.float64(0.05119632185241429)),
 (213, np.float64(0.05105170850323435)),
 (173, np.float64(0.05076083821594343)),
 (718, np.float64(0.0506945434033297)),
 (165, np.float64(0.05038129991206298)),
 (167, np.float64(0.050020147011468244)),
 (57, np.float64(0.049859540193304075)),
 (770, np.float64(0.04984795944228543)),
 (794, np.float64(0.04955542569738499)),
 (1175, np.float64(0.04900339370005184)),
 (1391, np.float64(0.04890303165828537)),
 (316, np.float64(0.04876242036052144)),
 (641, np.float64(0.048693290796117235)),
 (159, np.float64(0.048601390139013365)),
 (61, np.float64(0.0485441110983388)),
 (30, np.float64(0.0484952181074783)),
 (470, np.float64(0.048315743365949564)),
 (493, np.float64(0.04802290695076811)),
 (1165, np.float64(0.048013564425433204)),
 (1492, np.float64(0.04771341303150855)),
 (228, np.float64(0.047414663967565246)),
 (209, np.float64(0.04737793516369815)),
 (715, np.float64(0.04722002232848359)),
 (7, np.float64(0.047086094289856335)),
 (329, np.float64(0.046962697520312804)),
 (117, np.float64(0.04691880718005688)),
 (553, np.float64(0.04690132341595009)),
 (18, np.float64(0.046794439780267344)),
 (123, np.float64(0.046767215049132824)),
 (825, np.float64(0.0466428236819644)),
 (1148, np.float64(0.04648030192413899)),
 (29, np.float64(0.046346054649246814)),
 (156, np.float64(0.04634532948166929)),
 (401, np.float64(0.04630570449215961)),
 (161, np.float64(0.046304248691939484)),
 (658, np.float64(0.046296322143653826)),
 (14, np.float64(0.04609471284773382)),
 (1315, np.float64(0.04609237422352457)),
 (1120, np.float64(0.046070965235893)),
 (738, np.float64(0.0460413342238792)),
 (1484, np.float64(0.04601116440146591)),
 (639, np.float64(0.045807053582535215)),
 (976, np.float64(0.04553872132176578)),
 (821, np.float64(0.04543997875174183)),
 (699, np.float64(0.04523520332113827)),
 (1012, np.float64(0.04505188171187222)),
 (1091, np.float64(0.04481792225866198)),
 (924, np.float64(0.04462991237977747)),
 (461, np.float64(0.044609410785822395)),
 (1234, np.float64(0.04446621540912386)),
 (95, np.float64(0.044443007145001115)),
 (1405, np.float64(0.044268560530164036)),
 (1328, np.float64(0.044253578903687016)),
 (409, np.float64(0.04417100394316827)),
 (233, np.float64(0.0441288390502443)),
 (1480, np.float64(0.04404360471143998)),
 (1409, np.float64(0.043898131537234014)),
 (1414, np.float64(0.043849631915878776)),
 (838, np.float64(0.04378812405138556)),
 (230, np.float64(0.04362502615269767)),
 (88, np.float64(0.0435676040315307)),
 (822, np.float64(0.04347209589495544)),
 (954, np.float64(0.043407727404073435)),
 (1220, np.float64(0.043369721603939884)),
 (434, np.float64(0.0427201142256155)),
 (138, np.float64(0.04252700345532494)),
 (1214, np.float64(0.04242431391227335)),
 (1360, np.float64(0.0423621436178077)),
 (428, np.float64(0.04232150303281495)),
 (413, np.float64(0.042222099855043306)),
 (831, np.float64(0.042162854878830834)),
 (568, np.float64(0.04204136222366546)),
 (46, np.float64(0.04187617194336996)),
 (496, np.float64(0.041873808403540935)),
 (298, np.float64(0.04185132743569443)),
 (2, np.float64(0.0418234625822632)),
 (1105, np.float64(0.04178486522230035)),
 (1438, np.float64(0.04176716559762286)),
 (1173, np.float64(0.04168552072375999)),
 (314, np.float64(0.04157378762660272)),
 (268, np.float64(0.04153882889234521)),
 (189, np.float64(0.04152626688739759)),
 (588, np.float64(0.04148833483486977)),
 (805, np.float64(0.04146249766230977)),
 (212, np.float64(0.041429751129299974)),
 (985, np.float64(0.04142892926405799)),
 (1347, np.float64(0.041407158792196634)),
 (44, np.float64(0.041384588274181136)),
 (1422, np.float64(0.04132555059500737)),
 (576, np.float64(0.04129773327536523)),
 (734, np.float64(0.04128927291439162)),
 (528, np.float64(0.04116545221955198)),
 (867, np.float64(0.041088311617826334)),
 (1357, np.float64(0.04107353022530873)),
 (847, np.float64(0.0410104348730639)),
 (446, np.float64(0.040861203973240126)),
 (827, np.float64(0.04080378217291775)),
 (49, np.float64(0.04071894214582708)),
 (1298, np.float64(0.04071520390615178)),
 (731, np.float64(0.040598548171316126)),
 (605, np.float64(0.04055130164127889)),
 (293, np.float64(0.0405306310602248)),
 (1388, np.float64(0.04051859236211333)),
 (405, np.float64(0.04051846171793579)),
 (876, np.float64(0.040203962337932775)),
 (324, np.float64(0.04015597852849232)),
 (793, np.float64(0.040145016012928844)),
 (932, np.float64(0.04010197061669144)),
 (1113, np.float64(0.04003180164699488)),
 (1116, np.float64(0.04002553157952116)),
 (330, np.float64(0.03992850783709337)),
 (1233, np.float64(0.03987219716619767)),
 (1020, np.float64(0.03986126181508104)),
 (25, np.float64(0.03985987437590601)),
 (155, np.float64(0.039850872245311704)),
 (507, np.float64(0.03978446840922454)),
 (326, np.float64(0.039689807150667694)),
 (1383, np.float64(0.0396366289111689)),
 (565, np.float64(0.03960984905957362)),
 (1318, np.float64(0.03959097786843594)),
 (602, np.float64(0.0395472218525)),
 (187, np.float64(0.03943420288972638)),
 (1041, np.float64(0.03934475590315144)),
 (1014, np.float64(0.0391756721221512)),
 (1106, np.float64(0.03914090299911134)),
 (1275, np.float64(0.03911099097979025)),
 (383, np.float64(0.03909965064286873)),
 (51, np.float64(0.03909419597227299)),
 (1030, np.float64(0.03902644664514361)),
 (1382, np.float64(0.0389901187350714)),
 (174, np.float64(0.038979803370757)),
 (962, np.float64(0.038731259510941404)),
 (1481, np.float64(0.03872217704240942)),
 (77, np.float64(0.03867815012401339)),
 (595, np.float64(0.03862595558708571)),
 (610, np.float64(0.03859515135102122)),
 (490, np.float64(0.038549996810863206)),
 (412, np.float64(0.03844671852469586)),
 (127, np.float64(0.038428908272460906)),
 (335, np.float64(0.03835541591583637)),
 (374, np.float64(0.03833101460920251)),
 (478, np.float64(0.038251901863237986)),
 (310, np.float64(0.03824915960041959)),
 (222, np.float64(0.03813905874900927)),
 (669, np.float64(0.03813833614399565)),
 (31, np.float64(0.03813463686249972)),
 (447, np.float64(0.03795266237288601)),
 (676, np.float64(0.03784761056056225)),
 (709, np.float64(0.03780759368707946)),
 (5, np.float64(0.037745634555254995)),
 (110, np.float64(0.03763838730253675)),
 (86, np.float64(0.03752467288637621)),
 (1203, np.float64(0.03752074393430198)),
 (162, np.float64(0.037455332737675706)),
 (1000, np.float64(0.03742018506069675)),
 (1467, np.float64(0.03741854383076119)),
 (91, np.float64(0.037412821474563034)),
 (450, np.float64(0.03736385830956369)),
 (1239, np.float64(0.03734825387497978)),
 (449, np.float64(0.03732098673828836)),
 (762, np.float64(0.03721548435125274)),
 (39, np.float64(0.037045292233747786)),
 (580, np.float64(0.03702056378826925)),
 (458, np.float64(0.03701638952303171)),
 (118, np.float64(0.036985058260516616)),
 (196, np.float64(0.03697251976170034)),
 (203, np.float64(0.03685447802896806)),
 (1330, np.float64(0.036799352263345866)),
 (199, np.float64(0.036798161064330204)),
 (354, np.float64(0.036708937504341656)),
 (849, np.float64(0.03658150815917627)),
 (1437, np.float64(0.03650628309078695)),
 (1022, np.float64(0.03649566317589354)),
 (411, np.float64(0.03646844960159366)),
 (417, np.float64(0.03641203011650439)),
 (1170, np.float64(0.036395832656772056)),
 (323, np.float64(0.036374597129622134)),
 (1412, np.float64(0.03635105196276568)),
 (665, np.float64(0.03626443385362806)),
 (172, np.float64(0.036211150766207956)),
 (163, np.float64(0.03614691426169325)),
 (126, np.float64(0.03614466433185118)),
 (182, np.float64(0.03606998339660787)),
 (429, np.float64(0.036040836770313826)),
 (663, np.float64(0.035865803827508674)),
 (73, np.float64(0.03586227070655558)),
 (683, np.float64(0.03579672153274355)),
 (1243, np.float64(0.03574930592900734)),
 (1311, np.float64(0.03571937018972101)),
 (32, np.float64(0.03561391320893742)),
 (874, np.float64(0.03556848972286838)),
 (139, np.float64(0.03552193833364386)),
 (8, np.float64(0.035220073904948516)),
 (142, np.float64(0.03519900804412762)),
 (1474, np.float64(0.035115902389704384)),
 (35, np.float64(0.035057687114723006)),
 (852, np.float64(0.035046595360562774)),
 (106, np.float64(0.035027017069062014)),
 (444, np.float64(0.03499512181961594)),
 (1415, np.float64(0.034939273209146346)),
 (384, np.float64(0.034933235422939274)),
 (1381, np.float64(0.0349098948814082)),
 (747, np.float64(0.03475951717235345)),
 (664, np.float64(0.034677004123713634)),
 (376, np.float64(0.03459977366780551)),
 (1145, np.float64(0.03459253035095807)),
 (1114, np.float64(0.034451569282637734)),
 (291, np.float64(0.034440401615089856)),
 (1187, np.float64(0.03443390445070277)),
 (422, np.float64(0.03435770191871647)),
 (1386, np.float64(0.034303898570724495)),
 (1057, np.float64(0.034268903864771605)),
 (549, np.float64(0.034247509047062794)),
 (441, np.float64(0.034227561625148326)),
 (47, np.float64(0.034199023890724656)),
 (307, np.float64(0.03419343477891805)),
 (266, np.float64(0.03417227457790563)),
 (1225, np.float64(0.03416010184505128)),
 (146, np.float64(0.0341503062474553)),
 (425, np.float64(0.03414261673270981)),
 (743, np.float64(0.034026877921562726)),
 (934, np.float64(0.0340215281967086)),
 (1468, np.float64(0.03393237790126526)),
 (1227, np.float64(0.03390403449573723)),
 (1086, np.float64(0.03387061556886816)),
 (92, np.float64(0.03379114481312382)),
 (55, np.float64(0.033765370248766746)),
 (577, np.float64(0.033755293147214954)),
 (1416, np.float64(0.03375247912858683)),
 (707, np.float64(0.033745726707098106)),
 (955, np.float64(0.03366678080244597)),
 (1342, np.float64(0.03366490139947281)),
 (920, np.float64(0.03363824310273489)),
 (397, np.float64(0.03349999403155533)),
 (390, np.float64(0.0334997334802864)),
 (819, np.float64(0.033491586815446915)),
 (559, np.float64(0.0334511136773832)),
 (1167, np.float64(0.0334378267096547)),
 (80, np.float64(0.03340018886119648)),
 (144, np.float64(0.03339353898178863)),
 (1408, np.float64(0.0332071675420413)),
 (1153, np.float64(0.03319969736001428)),
 (343, np.float64(0.03319358892680381)),
 (1483, np.float64(0.033178395855524734)),
 (935, np.float64(0.03315187802454602)),
 (1042, np.float64(0.03311254993414339)),
 (313, np.float64(0.03306160314070722)),
 (19, np.float64(0.03305059424589993)),
 (1201, np.float64(0.032975547003204625)),
 (50, np.float64(0.032928924256242456)),
 (120, np.float64(0.0328874232948288)),
 (1390, np.float64(0.03287736168928968)),
 (536, np.float64(0.03282691697366891)),
 (779, np.float64(0.0326157454117249)),
 (334, np.float64(0.032597491046894654)),
 (1442, np.float64(0.03242354357964715)),
 (98, np.float64(0.03240265164626213)),
 (342, np.float64(0.03228943316865567)),
 (965, np.float64(0.03228264348421636)),
 (1092, np.float64(0.032255616025155254)),
 (1206, np.float64(0.03220423556647071)),
 (575, np.float64(0.03218950939952056)),
 (66, np.float64(0.03210968776566739)),
 (273, np.float64(0.03206701407391807)),
 (278, np.float64(0.03204994949688363)),
 (904, np.float64(0.03199509689639764)),
 (1117, np.float64(0.03198816081050805)),
 (129, np.float64(0.031974205410257805)),
 (226, np.float64(0.0319557982756251)),
 (907, np.float64(0.03193911256943205)),
 (939, np.float64(0.031921027309367744)),
 (931, np.float64(0.03187840962758267)),
 (270, np.float64(0.0317730219372491)),
 (69, np.float64(0.031683667822219166)),
 (1154, np.float64(0.031678283369146756)),
 (510, np.float64(0.03167720455568779)),
 (466, np.float64(0.031540697533218615)),
 (183, np.float64(0.0315051064105516)),
 (1387, np.float64(0.03144130767559478)),
 (333, np.float64(0.03139100656128902)),
 (1099, np.float64(0.03136094282433493)),
 (360, np.float64(0.031286875685513964)),
 (193, np.float64(0.03128651753268657)),
 (473, np.float64(0.03127027132837935)),
 (1450, np.float64(0.031216553917141784)),
 (472, np.float64(0.031198705789900135)),
 (626, np.float64(0.031114294721135746)),
 (1192, np.float64(0.031033715965097984)),
 (377, np.float64(0.030993503874023165)),
 (717, np.float64(0.030991682213429954)),
 (1364, np.float64(0.030990794106487696)),
 (1423, np.float64(0.030954466009116506)),
 (175, np.float64(0.030926733704019087)),
 (914, np.float64(0.0309064066971933)),
 (192, np.float64(0.03090217899784948)),
 (837, np.float64(0.030828216248448843)),
 (134, np.float64(0.030827571838199154)),
 (100, np.float64(0.030813608257294192)),
 (527, np.float64(0.030803192952500093)),
 (1108, np.float64(0.030782837968059737)),
 (403, np.float64(0.030742944765063764)),
 (379, np.float64(0.030714249741178472)),
 (855, np.float64(0.030702838223165024)),
 (477, np.float64(0.03066318758966116)),
 (532, np.float64(0.030647876056794185)),
 (930, np.float64(0.030513406006056433)),
 (1400, np.float64(0.030411248040922594)),
 (749, np.float64(0.03040343560852096)),
 (10, np.float64(0.03035228581133554)),
 (198, np.float64(0.030346869630388507)),
 (684, np.float64(0.030300372819064357)),
 (318, np.float64(0.030284161538285753)),
 (789, np.float64(0.030252651441695175)),
 (1307, np.float64(0.030211667191524315)),
 (1229, np.float64(0.03020368547906014)),
 (1178, np.float64(0.02999674246432022)),
 (1156, np.float64(0.029926683865436364)),
 (114, np.float64(0.029918282155050706)),
 (901, np.float64(0.02989445245213272)),
 (474, np.float64(0.02980659183792568)),
 (131, np.float64(0.029791093170460803)),
 (303, np.float64(0.029773033502750013)),
 (259, np.float64(0.02969850632269562)),
 (157, np.float64(0.02968967125138912)),
 (555, np.float64(0.029683711959632392)),
 (923, np.float64(0.029677950625341863)),
 (438, np.float64(0.029626815359126292)),
 (792, np.float64(0.029603129097567737)),
 (973, np.float64(0.029545973857693336)),
 (546, np.float64(0.02945723507989674)),
 (1147, np.float64(0.029420794179632243)),
 (65, np.float64(0.029415733554265733)),
 (194, np.float64(0.029410484363593933)),
 (210, np.float64(0.029407741112438407)),
 (170, np.float64(0.029386753918685657)),
 (682, np.float64(0.029370369064922675)),
 (321, np.float64(0.02932865195430595)),
 (1213, np.float64(0.02931908046997236)),
 (427, np.float64(0.029291745927159475)),
 (1248, np.float64(0.029272233725938596)),
 (721, np.float64(0.029267494132208437)),
 (785, np.float64(0.029257118932763122)),
 (227, np.float64(0.02916654060099813)),
 (489, np.float64(0.02914387280298206)),
 (655, np.float64(0.029134203814673423)),
 (497, np.float64(0.029109916712720257)),
 (979, np.float64(0.02908364489626352)),
 (1329, np.float64(0.029081186319271316)),
 (85, np.float64(0.029077905686351692)),
 (1455, np.float64(0.029076560710823714)),
 (630, np.float64(0.029056831952620484)),
 (28, np.float64(0.02904701954046659)),
 (751, np.float64(0.029004956867273873)),
 (361, np.float64(0.02893852117037258)),
 (190, np.float64(0.028864740207424657)),
 (1008, np.float64(0.02886470879152117)),
 (875, np.float64(0.028861195488576834)),
 (1160, np.float64(0.028857965934058066)),
 (562, np.float64(0.02879854738584819)),
 (136, np.float64(0.028665981394999575)),
 (6, np.float64(0.028624883822345053)),
 (732, np.float64(0.0286114947152036)),
 (457, np.float64(0.028589416286612476)),
 (304, np.float64(0.02857418696118892)),
 (104, np.float64(0.028564940370559327)),
 (498, np.float64(0.02856252944026237)),
 (1218, np.float64(0.02852564675392468)),
 (1085, np.float64(0.028486805228990428)),
 (1284, np.float64(0.02848063520664256)),
 (611, np.float64(0.028446902392325918)),
 (1144, np.float64(0.028438868158685376)),
 (261, np.float64(0.028438063512275832)),
 (1010, np.float64(0.02840218404201949)),
 (554, np.float64(0.02833963282053244)),
 (1451, np.float64(0.02828952729948931)),
 (4, np.float64(0.02820417526729192)),
 (1241, np.float64(0.028148789486590192)),
 (634, np.float64(0.028065256798282884)),
 (494, np.float64(0.02797507945118055)),
 (94, np.float64(0.027968764112956252)),
 (48, np.float64(0.027869134458612985)),
 (988, np.float64(0.027853371872994515)),
 (435, np.float64(0.027810134339729082)),
 (535, np.float64(0.027725088814706186)),
 (739, np.float64(0.027714901776329882)),

In [128]:
# The below is code for top 20 Highest recommended movies
for i in sorted_similar_score[:40]:
    print(df[df.index == i[0]]['title'])

285    The Other Guys
Name: title, dtype: object
Series([], Name: title, dtype: object)
87    Tomorrowland
Name: title, dtype: object
301    Cloud Atlas
Name: title, dtype: object
Series([], Name: title, dtype: object)
16    The Avengers
Name: title, dtype: object
693    Gone Girl
Name: title, dtype: object
885    The Break-Up
Name: title, dtype: object
160    How to Train Your Dragon 2
Name: title, dtype: object
40    Cars 2
Name: title, dtype: object
1323    City of Ember
Name: title, dtype: object
643    Space Cowboys
Name: title, dtype: object
Series([], Name: title, dtype: object)
Series([], Name: title, dtype: object)
Series([], Name: title, dtype: object)
Series([], Name: title, dtype: object)
Series([], Name: title, dtype: object)
Series([], Name: title, dtype: object)
Series([], Name: title, dtype: object)
101    X-Men: First Class
Name: title, dtype: object
188    Salt
Name: title, dtype: object
Series([], Name: title, dtype: object)
Series([], Name: title, dtype: object)
402    The Rundown
Name: title, dtype: object
370    Now You See Me 2
Name: title, dtype: object
Series([], Name: title, dtype: object)
622    Body of Lies
Name: title, dtype: object
Series([], Name: title, dtype: object)
521    The Terminal
Name: title, dtype: object
68    Iron Man
Name: title, dtype: object
0    Avatar
Name: title, dtype: object
Series([], Name: title, dtype: object)
Series([], Name: title, dtype: object)
899    Shrek
Name: title, dtype: object
237    The Huntsman: Winter's War
Name: title, dtype: object
1312    Angel Eyes
Name: title, dtype: object
Series([], Name: title, dtype: object)
Series([], Name: title, dtype: object)
Series([], Name: title, dtype: object)
Series([], Name: title, dtype: object)